"""Shared fixtures and configuration for univariate GARCH model tests.

Supplements the top-level ``tests/conftest.py`` which provides:
- ATOL = 1e-6 and RTOL = 1e-4 tolerance constants
- ``fixture_dir`` — root fixture directory resolver (supports MFE_FIXTURE_DIR)
- ``load_fixture_npy()`` / ``load_fixture_csv()`` — generic fixture loading
- ``assert_allclose()`` — convenience wrapper for numerical parity checks
- ``rng`` — ``numpy.random.default_rng(42)`` shared random generator

This file provides **univariate-specific** fixtures and helpers:

Fixtures:
    univariate_fixture_dir : Path
        Path to ``tests/fixtures/univariate/`` directory (session-scoped).
        Skips all tests if directory does not exist.
    univariate_data : np.ndarray
        Standard T=1000 return series, demeaned, scaled ~N(0, 0.01²)
        (session-scoped).
    univariate_data_short : np.ndarray
        Short T=200 return series for quick tests (session-scoped).
    heavy_bivariate_data : np.ndarray
        T×2 bivariate data for HEAVY model tests (session-scoped).
    default_garch_params : np.ndarray
        Default GARCH(1,1) parameter vector [omega, alpha, beta].
    default_tarch_params : np.ndarray
        Default TARCH(1,1,1) parameter vector [omega, alpha, gamma, beta].
    default_agarch_params : np.ndarray
        Default AGARCH(1,1) parameter vector [omega, alpha, gamma, beta].
    default_egarch_params : np.ndarray
        Default EGARCH(1,1,1) parameter vector [omega, alpha, gamma, beta].
    default_figarch_params : np.ndarray
        Default FIGARCH(1,d,1) parameter vector [omega, phi, d, beta].
    default_igarch_params : np.ndarray
        Default IGARCH(1,1) parameter vector [omega, alpha].
    default_aparch_params : np.ndarray
        Default APARCH(1,1,1) parameter vector
        [omega, alpha, gamma, beta, delta].

Helper Functions:
    load_univariate_fixture(fixture_dir, model_name, fixture_name)
        Load a model-specific .npy fixture from the univariate fixtures dir.
    load_univariate_input(fixture_dir, model_name)
        Load the input data .npy fixture used for MATLAB reference estimation.

Custom Markers:
    parity
        Marks tests requiring MATLAB fixture comparison.
    requires_fixtures
        Marks tests that need fixture files generated by
        ``scripts/generate_fixtures.m``.
    slow
        Marks tests that may take >5 seconds (deselect with
        ``-m 'not slow'``).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import pytest


# ---------------------------------------------------------------------------
# Pytest Configuration Hook — Custom Marker Registration
# ---------------------------------------------------------------------------

def pytest_configure(config: Any) -> None:
    """Register custom markers for univariate GARCH model tests.

    Markers registered here supplement those from the parent
    ``tests/conftest.py``.  Duplicate registrations are harmless — pytest
    silently deduplicates.

    Markers
    -------
    parity
        Marks tests that compare Python outputs against MATLAB reference
        fixture files using ``numpy.testing.assert_allclose`` with
        ``atol=1e-6, rtol=1e-4``.
    requires_fixtures
        Marks tests that require generated fixture files from
        ``scripts/generate_fixtures.m`` + ``scripts/convert_fixtures.py``.
    slow
        Marks tests that may take >5 seconds to execute (deselect with
        ``-m 'not slow'``).
    """
    config.addinivalue_line(
        "markers",
        "parity: marks tests requiring MATLAB fixture comparison",
    )
    config.addinivalue_line(
        "markers",
        "requires_fixtures: marks tests that need fixture files",
    )
    config.addinivalue_line(
        "markers",
        "slow: marks tests that may take >5 seconds "
        "(deselect with -m 'not slow')",
    )


# ---------------------------------------------------------------------------
# Session-Scoped Fixtures — Fixture Directory
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def univariate_fixture_dir(fixture_dir: Path) -> Path:
    """Path to ``tests/fixtures/univariate/`` directory.

    Resolves the fixture directory containing MATLAB reference outputs for
    all 7 GARCH model families (AGARCH, APARCH, EGARCH, FIGARCH, HEAVY,
    IGARCH, TARCH).  Uses the ``fixture_dir`` fixture from the parent
    ``tests/conftest.py``.

    If the directory does not exist the entire test collection scoped under
    this fixture is skipped gracefully, allowing the test suite to degrade
    cleanly before fixtures have been generated.

    Parameters
    ----------
    fixture_dir : Path
        Base fixture directory from parent conftest.

    Returns
    -------
    Path
        ``fixture_dir / "univariate"`` if it exists.

    Raises
    ------
    pytest.skip
        When the univariate fixtures directory is not found on disk.
    """
    path: Path = fixture_dir / "univariate"
    if not path.exists():
        pytest.skip(
            "Univariate fixtures not found; "
            "run scripts/generate_fixtures.m first"
        )
    return path


# ---------------------------------------------------------------------------
# Session-Scoped Fixtures — Standard Test Data
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def univariate_data() -> np.ndarray:
    """Generate standardised test return data for univariate GARCH estimation.

    Creates a T = 1000 return series using ``numpy.random.default_rng(42)``
    that is:

    * Scaled by 0.01 to resemble daily financial returns
      (mean ≈ 0, std ≈ 0.01–0.02).
    * Demeaned so the mean-zero assumption required by all GARCH model
      families is satisfied.

    The deterministic seed guarantees reproducible test data across runs
    and platforms, matching the MATLAB fixture generation script
    (``rng(42, 'twister')``).

    Returns
    -------
    np.ndarray
        Shape ``(1000,)`` mean-zero return series scaled to daily-return
        magnitude.
    """
    rng: np.random.Generator = np.random.default_rng(42)
    returns: np.ndarray = rng.standard_normal(1000) * 0.01
    # Demean to satisfy GARCH mean-zero assumption
    # Ref: generate_fixtures.m — epsilon = epsilon - mean(epsilon)
    returns = returns - returns.mean()
    return returns


@pytest.fixture(scope="session")
def univariate_data_short() -> np.ndarray:
    """Short T = 200 return series for quick tests.

    Identical generation methodology to :func:`univariate_data` but with
    only 200 observations.  Suitable for rapid smoke tests where full
    T = 1000 estimation would be unnecessarily slow.

    Returns
    -------
    np.ndarray
        Shape ``(200,)`` mean-zero return series scaled to daily-return
        magnitude.
    """
    rng: np.random.Generator = np.random.default_rng(42)
    returns: np.ndarray = rng.standard_normal(200) * 0.01
    # Demean to satisfy GARCH mean-zero assumption
    returns = returns - returns.mean()
    return returns


@pytest.fixture(scope="session")
def heavy_bivariate_data() -> np.ndarray:
    """Generate T × K = 2 bivariate data for HEAVY model tests.

    The HEAVY (High-frEquency-bAsed VolatilitY) model of Shephard and
    Sheppard requires a T × K matrix where each column represents a
    different observable.  The standard bivariate specification uses:

    * **Column 0** — Squared returns (return variance proxy).
    * **Column 1** — Realized measure proxy (absolute returns scaled by
      uniform noise in [0.8, 1.2]).

    Both columns are guaranteed non-negative, satisfying the HEAVY model's
    positivity requirements.

    Returns
    -------
    np.ndarray
        Shape ``(500, 2)`` non-negative bivariate data matrix.
    """
    rng: np.random.Generator = np.random.default_rng(42)
    T: int = 500
    returns: np.ndarray = rng.standard_normal(T) * 0.01
    # Realized measure proxy: |returns| × uniform noise ∈ [0.8, 1.2]
    realized: np.ndarray = np.abs(returns) * rng.uniform(0.8, 1.2, T)
    data: np.ndarray = np.column_stack([returns ** 2, realized])
    return data


# ---------------------------------------------------------------------------
# Function-Scoped Fixtures — Default Model Parameters
# ---------------------------------------------------------------------------
# Each fixture returns a numpy array of typical financial parameters for the
# corresponding GARCH model family.  All parameter values satisfy the
# model-specific stationarity, positivity, and range constraints documented
# in the MATLAB source headers.
#
# These are function-scoped (the default) because test code may modify them
# in-place without corrupting other tests.

@pytest.fixture
def default_garch_params() -> np.ndarray:
    """Default GARCH(1,1) parameters: ``[omega, alpha, beta]``.

    Typical financial calibration:

    * omega = 1e-5  (intercept / long-run variance component)
    * alpha = 0.05  (ARCH coefficient — shock sensitivity)
    * beta  = 0.90  (GARCH coefficient — persistence)

    Stationarity check: alpha + beta = 0.95 < 1 ✓

    Returns
    -------
    np.ndarray
        Shape ``(3,)`` parameter vector.
    """
    return np.array([1e-5, 0.05, 0.90])


@pytest.fixture
def default_tarch_params() -> np.ndarray:
    """Default TARCH(1,1,1) parameters: ``[omega, alpha, gamma, beta]``.

    Typical financial calibration with leverage:

    * omega = 1e-5
    * alpha = 0.03  (symmetric ARCH coefficient)
    * gamma = 0.04  (asymmetric / leverage coefficient)
    * beta  = 0.90  (GARCH persistence)

    Stationarity check: alpha + 0.5 × gamma + beta = 0.03 + 0.02 + 0.90
    = 0.95 < 1 ✓

    Ref: tarch.m — constraint (4): sum(alpha + 0.5*gamma + beta) < 1

    Returns
    -------
    np.ndarray
        Shape ``(4,)`` parameter vector.
    """
    return np.array([1e-5, 0.03, 0.04, 0.90])


@pytest.fixture
def default_agarch_params() -> np.ndarray:
    """Default AGARCH(1,1) parameters: ``[omega, alpha, gamma, beta]``.

    Asymmetric GARCH (Engle 1990) calibration:

    * omega = 1e-5
    * alpha = 0.05  (ARCH coefficient)
    * gamma = 0.02  (asymmetry shift parameter)
    * beta  = 0.90  (GARCH persistence)

    Stationarity check (AGARCH): alpha + beta = 0.95 < 1 ✓

    Ref: agarch.m — h(t) = omega + alpha*(r_{t-1} - gamma)^2 + beta*h(t-1)

    Returns
    -------
    np.ndarray
        Shape ``(4,)`` parameter vector.
    """
    return np.array([1e-5, 0.05, 0.02, 0.90])


@pytest.fixture
def default_egarch_params() -> np.ndarray:
    """Default EGARCH(1,1,1) parameters: ``[omega, alpha, gamma, beta]``.

    Exponential GARCH (Nelson 1991) calibration.  Note that EGARCH operates
    in **log-variance space**, so omega can be negative:

    * omega = -0.1   (log-variance intercept — negative is valid)
    * alpha = 0.05   (magnitude effect)
    * gamma = -0.1   (sign / leverage effect — negative means negative
      shocks increase volatility more)
    * beta  = 0.95   (log-variance persistence)

    Stationarity is enforced by roots of [1, -beta] polynomial having
    modulus < 1.  With beta = 0.95, the single root is 0.95 < 1 ✓

    Ref: egarch.m — ln(h(t)) = omega + alpha*(|z|-C) + gamma*z + beta*ln(h)

    Returns
    -------
    np.ndarray
        Shape ``(4,)`` parameter vector.
    """
    return np.array([-0.1, 0.05, -0.1, 0.95])


@pytest.fixture
def default_figarch_params() -> np.ndarray:
    """Default FIGARCH(1,d,1) parameters: ``[omega, phi, d, beta]``.

    Fractionally Integrated GARCH calibration:

    * omega = 1e-5   (intercept)
    * phi   = 0.1    (AR coefficient of the ARCH(∞) polynomial)
    * d     = 0.45   (fractional differencing — long memory parameter,
      0 < d < 1)
    * beta  = 0.3    (MA coefficient of the ARCH(∞) polynomial)

    Constraint checks:
    - 0 < d < 1 ✓
    - phi ≥ 0 ✓
    - beta ≥ 0 ✓
    - beta ≤ d + phi = 0.55 ✓

    Ref: figarch.m — h(t) = omega/(1-beta) + sum(lambda_i * eps(t-i)^2)

    Returns
    -------
    np.ndarray
        Shape ``(4,)`` parameter vector.
    """
    return np.array([1e-5, 0.1, 0.45, 0.3])


@pytest.fixture
def default_igarch_params() -> np.ndarray:
    """Default IGARCH(1,1) parameters: ``[omega, alpha]``.

    Integrated GARCH calibration.  The unit-root constraint means
    ``alpha + beta = 1`` exactly, so ``beta = 1 - alpha`` is **not
    estimated** — it is computed from the constraint:

    * omega = 1e-5   (intercept — may optionally be zero)
    * alpha = 0.1    (ARCH coefficient)
    * (implied) beta = 0.9

    Unit-root: alpha + beta = 0.1 + 0.9 = 1.0 ✓

    Ref: igarch.m — beta(q) = 1 - sum(alpha) - sum(beta(1:q-1))

    Returns
    -------
    np.ndarray
        Shape ``(2,)`` parameter vector (beta is NOT in the vector).
    """
    return np.array([1e-5, 0.1])


@pytest.fixture
def default_aparch_params() -> np.ndarray:
    """Default APARCH(1,1,1) parameters:
    ``[omega, alpha, gamma, beta, delta]``.

    Asymmetric Power ARCH (Ding, Granger & Engle 1993) calibration:

    * omega = 1e-5   (intercept)
    * alpha = 0.05   (ARCH coefficient, alpha ≥ 0)
    * gamma = 0.5    (asymmetry / leverage, -1 < gamma < 1)
    * beta  = 0.85   (GARCH persistence, beta ≥ 0)
    * delta = 2.0    (power parameter, 0.3 ≤ delta ≤ 4.0)

    Stationarity check: alpha + beta = 0.90 < 1 ✓
    Delta = 2.0 reduces APARCH to the GJR-GARCH / TARCH(squared) case.

    Ref: aparch.m — h(t)^(delta/2) = omega + alpha*(|r|-gamma*r)^delta
                    + beta*h(t-1)^(delta/2)

    Returns
    -------
    np.ndarray
        Shape ``(5,)`` parameter vector.
    """
    return np.array([1e-5, 0.05, 0.5, 0.85, 2.0])


# ---------------------------------------------------------------------------
# Helper Functions — Fixture Loading
# ---------------------------------------------------------------------------

def load_univariate_fixture(
    fixture_dir: Path,
    model_name: str,
    fixture_name: str,
) -> np.ndarray:
    """Load a specific ``.npy`` fixture file for a univariate GARCH model.

    Constructs the path ``fixture_dir / model_name / fixture_name.npy``
    and loads the array.  If the file does not exist the calling test is
    gracefully skipped via ``pytest.skip``.

    Parameters
    ----------
    fixture_dir : Path
        Path to the univariate fixtures directory
        (``tests/fixtures/univariate``).
    model_name : str
        Model subdirectory name, e.g. ``'agarch'``, ``'tarch'``,
        ``'egarch'``.
    fixture_name : str
        Fixture file base name (without ``.npy`` extension), e.g.
        ``'parameters'``, ``'ht'``, ``'loglikelihood'``.

    Returns
    -------
    np.ndarray
        Array loaded from the fixture file.

    Raises
    ------
    pytest.skip
        When the requested fixture file is not found on disk.
    """
    path: Path = fixture_dir / model_name / f"{fixture_name}.npy"
    if not path.exists():
        pytest.skip(f"Fixture {path} not found")
    # allow_pickle=True for object-dtype arrays containing dicts of test
    # cases generated by convert_fixtures.py.  These files are committed to
    # the repository and are NOT user-supplied.
    return np.load(path, allow_pickle=True)


def load_univariate_input(
    fixture_dir: Path,
    model_name: str,
) -> np.ndarray:
    """Load input data used for MATLAB reference estimation.

    Looks for ``fixture_dir / model_name / input_data.npy`` — the return
    series that was fed into the MATLAB estimator when generating the
    reference fixtures.

    Parameters
    ----------
    fixture_dir : Path
        Path to the univariate fixtures directory
        (``tests/fixtures/univariate``).
    model_name : str
        Model subdirectory name, e.g. ``'agarch'``, ``'tarch'``.

    Returns
    -------
    np.ndarray
        Input data array used for MATLAB reference estimation.

    Raises
    ------
    pytest.skip
        When the input data fixture is not found on disk.
    """
    path: Path = fixture_dir / model_name / "input_data.npy"
    if not path.exists():
        pytest.skip(f"Input fixture {path} not found")
    return np.load(path, allow_pickle=True)
