"""Pytest tests for mfe_toolbox.bootstrap.bsds — Hansen-White SPA/BSDS test.

Tests verify:
- Input validation (correct errors raised for invalid inputs)
- Output shapes and types (3 float p-values in [0, 1])
- P-value bounds (0 <= p <= 1 for all three p-values)
- Statistical properties (p-values respond correctly to clearly better/worse models)
- Studentized vs standard mode behavior
- Block vs stationary bootstrap dispatch
- Numerical parity against MATLAB reference fixtures (atol=1e-6, rtol=1e-4)
- Reproducibility with seeded RNG

Ref: bootstrap/bsds.m — Kevin Sheppard, Revision 3, 4/1/2007
"""

from pathlib import Path

import numpy as np
import numpy.testing as npt
import pytest

from mfe_toolbox.bootstrap.bsds import bsds

# ---------------------------------------------------------------------------
# Tolerance Constants
# ---------------------------------------------------------------------------
# Per AAP Section 0.7.1: numpy.testing.assert_allclose(actual, expected,
#     atol=1e-6, rtol=1e-4) is the standard for deterministic MATLAB parity.
ATOL: float = 1e-6
RTOL: float = 1e-4

# Bootstrap p-values are stochastic because the resampling indices are
# generated by unseeded RNGs inside block_bootstrap / stationary_bootstrap.
# Exact numerical parity with MATLAB fixtures is therefore not achievable
# without identical random-number streams.  The wider tolerance below is
# used for "soft" parity verification on bootstrap p-values.
BOOTSTRAP_PVAL_ATOL: float = 0.20


# ---------------------------------------------------------------------------
# Test Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def rng_local():
    """Seeded RNG for reproducible test data generation (local scope).

    Uses seed 12345 (different from conftest session-scoped seed 42) to
    avoid coupling with session-level fixtures consumed by other tests.
    """
    return np.random.default_rng(12345)


@pytest.fixture
def loss_data(rng_local):
    """Generate benchmark and model loss data for bsds testing.

    Creates T=200 observations with K=5 models.  Both benchmark and models
    use squared Gaussian losses so that p-values fall in a meaningful range.
    """
    T = 200
    K = 5
    bench = rng_local.standard_normal(T) ** 2  # squared losses
    models = rng_local.standard_normal((T, K)) ** 2  # model losses
    return bench, models


@pytest.fixture
def clearly_better_models(rng_local):
    """Models that are clearly better than benchmark (small p-values expected).

    Benchmark losses are inflated by a constant so that the comparison models
    have smaller average losses, driving the BSDS toward rejection.
    """
    T = 200
    K = 3
    bench = rng_local.standard_normal(T) ** 2 + 2.0  # inflated benchmark
    models = rng_local.standard_normal((T, K)) ** 2   # normal model losses
    return bench, models


@pytest.fixture
def clearly_worse_models(rng_local):
    """Models that are clearly worse than benchmark (large p-values expected).

    Model losses are inflated by a constant so that the benchmark has smaller
    average losses, driving the BSDS away from rejection.
    """
    T = 200
    K = 3
    bench = rng_local.standard_normal(T) ** 2          # normal benchmark
    models = rng_local.standard_normal((T, K)) ** 2 + 2.0  # inflated models
    return bench, models


# =========================================================================
# Input Validation Tests
# Ref: bsds.m:54-98
# =========================================================================

class TestBsdsInputValidation:
    """Tests that bsds raises ValueError for invalid inputs."""

    def test_bsds_bench_not_column_vector(self, rng_local):
        """Passing a matrix (T x 2) for bench should raise ValueError.

        Ref: bsds.m:76-78 — if kb>1 error('BENCH must be a column vector')
        """
        bench_matrix = rng_local.standard_normal((50, 2))
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="BENCH must be a column vector"):
            bsds(bench_matrix, models, B=100, w=5)

    def test_bsds_bench_too_short(self, rng_local):
        """Passing bench with length < 2 should raise ValueError.

        Ref: bsds.m:79-81 — if tb<2 error('BENCH must have at least 2 ...')
        """
        bench_short = np.array([1.0])
        models = np.array([[1.0]])
        with pytest.raises(ValueError, match="BENCH must have at least 2"):
            bsds(bench_short, models, B=100, w=1)

    def test_bsds_bench_empty(self):
        """Passing empty bench should raise ValueError."""
        bench_empty = np.array([])
        models = np.array([]).reshape(0, 1)
        with pytest.raises(ValueError):
            bsds(bench_empty, models, B=100, w=1)

    def test_bsds_bench_models_length_mismatch(self, rng_local):
        """bench and models with different T should raise ValueError.

        Ref: bsds.m:83-85 — if t~=tb error('BENCH and MODELS must have ...')
        """
        bench = rng_local.standard_normal(100)
        models = rng_local.standard_normal((50, 3))  # different T
        with pytest.raises(
            ValueError,
            match="BENCH and MODELS must have the same number of observations",
        ):
            bsds(bench, models, B=100, w=5)

    def test_bsds_B_zero(self, rng_local):
        """B=0 should raise ValueError.

        Ref: bsds.m:86-88 — if ~isscalar(B) || B<1 || floor(B)~=B
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="B must be a positive scalar integer"):
            bsds(bench, models, B=0, w=5)

    def test_bsds_B_negative(self, rng_local):
        """B=-1 should raise ValueError.

        Ref: bsds.m:86-88
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="B must be a positive scalar integer"):
            bsds(bench, models, B=-1, w=5)

    def test_bsds_B_non_integer(self, rng_local):
        """B=1.5 (non-integer) should raise ValueError.

        Ref: bsds.m:86-88 — floor(B)~=B
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="B must be a positive scalar integer"):
            bsds(bench, models, B=1.5, w=5)

    def test_bsds_w_zero(self, rng_local):
        """w=0 should raise ValueError.

        Ref: bsds.m:89-91 — if ~isscalar(w) || w<1 || floor(w)~=w
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="W must be a positive scalar integer"):
            bsds(bench, models, B=100, w=0)

    def test_bsds_w_negative(self, rng_local):
        """w=-1 should raise ValueError.

        Ref: bsds.m:89-91
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="W must be a positive scalar integer"):
            bsds(bench, models, B=100, w=-1)

    def test_bsds_w_non_integer(self, rng_local):
        """w=1.5 (non-integer) should raise ValueError.

        Ref: bsds.m:89-91 — floor(w)~=w
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(ValueError, match="W must be a positive scalar integer"):
            bsds(bench, models, B=100, w=1.5)

    def test_bsds_boot_invalid(self, rng_local):
        """boot='INVALID' should raise ValueError.

        Ref: bsds.m:93-95 — if ~ismember(boot,{'STATIONARY','BLOCK'})
        """
        bench = rng_local.standard_normal(50)
        models = rng_local.standard_normal((50, 3))
        with pytest.raises(
            ValueError,
            match="BOOT must be either 'STATIONARY' or 'BLOCK'",
        ):
            bsds(bench, models, B=100, w=5, boot="INVALID")


# =========================================================================
# Output Shape and Type Tests
# =========================================================================

class TestBsdsOutput:
    """Tests verifying return type, count, and value range of bsds outputs."""

    def test_bsds_returns_three_values(self, loss_data):
        """bsds must return exactly 3 values (c, u, l)."""
        bench, models = loss_data
        result = bsds(bench, models, B=50, w=5)
        assert isinstance(result, tuple), "bsds must return a tuple"
        assert len(result) == 3, "bsds must return exactly 3 values"

    def test_bsds_returns_float_scalars(self, loss_data):
        """All three returned values must be Python float scalars."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=50, w=5)
        assert isinstance(c, float), f"c must be float, got {type(c)}"
        assert isinstance(u, float), f"u must be float, got {type(u)}"
        assert isinstance(l, float), f"l must be float, got {type(l)}"

    def test_bsds_pvalues_in_valid_range(self, loss_data):
        """All 3 p-values must lie in [0, 1]."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10)
        assert 0.0 <= c <= 1.0, f"Consistent p-value {c} out of range [0, 1]"
        assert 0.0 <= u <= 1.0, f"Upper p-value {u} out of range [0, 1]"
        assert 0.0 <= l <= 1.0, f"Lower p-value {l} out of range [0, 1]"

    def test_bsds_pvalue_ordering(self, loss_data):
        """Hansen's SPA theory implies l <= c <= u.

        The lower p-value (l) treats all models worse than the benchmark as
        irrelevant; the consistent (c) uses a data-driven threshold; the
        upper (u, White's RC) re-centres at the sample mean.  Hence the
        ordering l <= c <= u should hold in general.
        """
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=200, w=10)
        assert l <= c + 1e-10, (
            f"Lower p-value {l} should be <= consistent p-value {c}"
        )
        assert c <= u + 1e-10, (
            f"Consistent p-value {c} should be <= upper p-value {u}"
        )

    def test_bsds_pvalues_valid_range_block(self, loss_data):
        """p-values must be in [0, 1] when using BLOCK bootstrap."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10, boot="BLOCK")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0


# =========================================================================
# Functional Tests
# =========================================================================

class TestBsdsFunctional:
    """Tests verifying statistical behaviour and mode dispatch."""

    def test_bsds_clearly_better_models_low_pvals(self, clearly_better_models):
        """When models are clearly better than benchmark, p-values should be small.

        Inflated benchmark losses make the models appear superior.  White's
        RC p-value (u) should detect this and be below 0.5.
        """
        bench, models = clearly_better_models
        c, u, l = bsds(bench, models, B=200, w=10)
        # The upper p-value should indicate outperformance (low)
        assert u < 0.5, (
            f"Upper (White RC) p-value {u} should be < 0.5 for clearly better models"
        )

    def test_bsds_clearly_worse_models_high_pvals(self, clearly_worse_models):
        """When models are clearly worse than benchmark, p-values should be large.

        Inflated model losses make the benchmark appear superior.  Hansen's
        consistent SPA p-value (c) should be large (> 0.3).
        """
        bench, models = clearly_worse_models
        c, u, l = bsds(bench, models, B=200, w=10)
        # The consistent p-value should not reject the null
        assert c > 0.3, (
            f"Consistent p-value {c} should be > 0.3 for clearly worse models"
        )

    def test_bsds_standard_mode(self, loss_data):
        """bsds with type_='STANDARD' (non-studentized) should run and return
        valid p-values."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10, type_="STANDARD")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_studentized_mode(self, loss_data):
        """bsds with type_='STUDENTIZED' (default) should run and return
        valid p-values."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10, type_="STUDENTIZED")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_block_bootstrap(self, loss_data):
        """bsds with boot='BLOCK' (circular block bootstrap) should run and
        return valid p-values."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10, boot="BLOCK")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_stationary_bootstrap(self, loss_data):
        """bsds with boot='STATIONARY' (Politis-Romano) should run and return
        valid p-values."""
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=100, w=10, boot="STATIONARY")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_single_model(self, rng_local):
        """bsds with K=1 model (edge case) should work correctly."""
        T = 100
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, 1)) ** 2
        c, u, l = bsds(bench, models, B=100, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_accepts_1d_bench(self, rng_local):
        """1-D array bench (not a column vector) should be auto-reshaped and
        accepted without error."""
        T = 100
        bench_1d = rng_local.standard_normal(T) ** 2
        assert bench_1d.ndim == 1, "Precondition: bench is 1-D"
        models = rng_local.standard_normal((T, 3)) ** 2
        c, u, l = bsds(bench_1d, models, B=100, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_accepts_column_bench(self, rng_local):
        """2-D column vector bench (T x 1) should be accepted."""
        T = 100
        bench_col = rng_local.standard_normal((T, 1)) ** 2
        assert bench_col.ndim == 2 and bench_col.shape[1] == 1
        models = rng_local.standard_normal((T, 3)) ** 2
        c, u, l = bsds(bench_col, models, B=100, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_standard_vs_studentized_differ(self, loss_data):
        """Standard and studentized modes should generally produce different
        p-values when losses are heteroskedastic."""
        bench, models = loss_data
        # Run both modes multiple times and check they produce valid results
        c_std, u_std, l_std = bsds(
            bench, models, B=100, w=10, type_="STANDARD"
        )
        c_stu, u_stu, l_stu = bsds(
            bench, models, B=100, w=10, type_="STUDENTIZED"
        )
        # Both should produce valid p-values
        for val in [c_std, u_std, l_std, c_stu, u_stu, l_stu]:
            assert 0.0 <= val <= 1.0

    def test_bsds_boot_case_insensitive(self, rng_local):
        """boot parameter should be case-insensitive (converted to upper)."""
        T = 100
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, 3)) ** 2
        # Lowercase 'stationary' should work
        c, u, l = bsds(bench, models, B=50, w=5, boot="stationary")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0
        # Mixed case 'Block' should work
        c2, u2, l2 = bsds(bench, models, B=50, w=5, boot="Block")
        assert 0.0 <= c2 <= 1.0
        assert 0.0 <= u2 <= 1.0
        assert 0.0 <= l2 <= 1.0


# =========================================================================
# Parity Tests Against MATLAB Fixtures
# =========================================================================

class TestBsdsParity:
    """Parity tests loading MATLAB-generated fixture data.

    Note on stochasticity:
    ----------------------
    Bootstrap p-values depend on random resampling indices generated inside
    ``block_bootstrap`` / ``stationary_bootstrap``.  These functions create
    their own unseeded ``np.random.default_rng()``, so each call to ``bsds``
    produces different p-values.  Exact numerical parity with MATLAB fixtures
    (which used MATLAB's own RNG) is therefore not achievable.

    The parity tests below verify:
    1. The function executes without error on the MATLAB fixture inputs.
    2. Returned p-values lie in [0, 1].
    3. The p-value ordering l <= c <= u holds.
    4. (Soft check) p-values are within a wider tolerance
       (BOOTSTRAP_PVAL_ATOL) of the MATLAB reference values.
    """

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_bsds_parity_npy_tc1_stationary_studentized(
        self, bootstrap_fixture_dir
    ):
        """Verify behaviour against MATLAB tc1: STUDENTIZED + STATIONARY.

        Fixture: bsds.npy -> tc1 (T=1000, K=10, B=1000, w=12)
        MATLAB results: c=0.812, u=0.812, l=0.58
        """
        fixture_path = bootstrap_fixture_dir / "bsds.npy"
        if not fixture_path.exists():
            pytest.skip("Fixture file not found: bsds.npy")

        fixture = np.load(fixture_path, allow_pickle=True).item()
        bench = fixture["tc1_bench"]
        models = fixture["tc1_models"]
        expected_c = fixture["tc1_c"]
        expected_u = fixture["tc1_u"]
        expected_l = fixture["tc1_l"]
        B = int(fixture["tc1_B"])
        w = int(fixture["tc1_w"])

        c, u, l = bsds(bench, models, B=B, w=w,
                        type_="STUDENTIZED", boot="STATIONARY")

        # Hard checks: p-values must be valid
        assert 0.0 <= c <= 1.0, f"c={c} out of range"
        assert 0.0 <= u <= 1.0, f"u={u} out of range"
        assert 0.0 <= l <= 1.0, f"l={l} out of range"
        assert l <= c + 1e-10, f"l={l} should be <= c={c}"
        assert c <= u + 1e-10, f"c={c} should be <= u={u}"

        # Soft parity check with wider tolerance for stochastic bootstrap.
        # Bootstrap p-values have inherent Monte Carlo variance; exact
        # reproduction requires identical random-number streams.
        npt.assert_allclose(
            c, expected_c, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Consistent p-val soft parity (tc1)",
        )
        npt.assert_allclose(
            u, expected_u, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Upper p-val soft parity (tc1)",
        )
        npt.assert_allclose(
            l, expected_l, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Lower p-val soft parity (tc1)",
        )

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_bsds_parity_npy_tc2_block_standard(
        self, bootstrap_fixture_dir
    ):
        """Verify behaviour against MATLAB tc2: STANDARD + BLOCK.

        Fixture: bsds.npy -> tc2 (T=1000, K=10, B=1000, w=12)
        MATLAB results: c=0.829, u=0.829, l=0.603
        """
        fixture_path = bootstrap_fixture_dir / "bsds.npy"
        if not fixture_path.exists():
            pytest.skip("Fixture file not found: bsds.npy")

        fixture = np.load(fixture_path, allow_pickle=True).item()
        bench = fixture["tc2_bench"]
        models = fixture["tc2_models"]
        expected_c = fixture["tc2_c"]
        expected_u = fixture["tc2_u"]
        expected_l = fixture["tc2_l"]
        B = int(fixture["tc2_B"])
        w = int(fixture["tc2_w"])

        c, u, l = bsds(bench, models, B=B, w=w,
                        type_="STANDARD", boot="BLOCK")

        # Hard checks: p-values must be valid
        assert 0.0 <= c <= 1.0, f"c={c} out of range"
        assert 0.0 <= u <= 1.0, f"u={u} out of range"
        assert 0.0 <= l <= 1.0, f"l={l} out of range"
        assert l <= c + 1e-10, f"l={l} should be <= c={c}"
        assert c <= u + 1e-10, f"c={c} should be <= u={u}"

        # Soft parity check
        npt.assert_allclose(
            c, expected_c, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Consistent p-val soft parity (tc2)",
        )
        npt.assert_allclose(
            u, expected_u, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Upper p-val soft parity (tc2)",
        )
        npt.assert_allclose(
            l, expected_l, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Lower p-val soft parity (tc2)",
        )

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_bsds_parity_npy_tc3_small_sample(
        self, bootstrap_fixture_dir
    ):
        """Verify behaviour against MATLAB tc3: small sample (T=200, K=3).

        Fixture: bsds.npy -> tc3 (T=200, K=3, B=500, w=8)
        MATLAB results: c=1.0, u=1.0, l=1.0
        """
        fixture_path = bootstrap_fixture_dir / "bsds.npy"
        if not fixture_path.exists():
            pytest.skip("Fixture file not found: bsds.npy")

        fixture = np.load(fixture_path, allow_pickle=True).item()
        bench = fixture["tc3_bench"]
        models = fixture["tc3_models"]
        expected_c = fixture["tc3_c"]
        expected_u = fixture["tc3_u"]
        expected_l = fixture["tc3_l"]
        B = int(fixture["tc3_B"])
        w = int(fixture["tc3_w"])

        c, u, l = bsds(bench, models, B=B, w=w,
                        type_="STUDENTIZED", boot="STATIONARY")

        # Hard checks: p-values must be valid
        assert 0.0 <= c <= 1.0, f"c={c} out of range"
        assert 0.0 <= u <= 1.0, f"u={u} out of range"
        assert 0.0 <= l <= 1.0, f"l={l} out of range"
        assert l <= c + 1e-10, f"l={l} should be <= c={c}"
        assert c <= u + 1e-10, f"c={c} should be <= u={u}"

        # tc3 expected all p-values = 1.0; when benchmark clearly dominates,
        # Python results should also be very high (close to 1.0).
        if expected_c == 1.0:
            assert c >= 0.7, f"Expected high c (MATLAB=1.0), got {c}"
        if expected_u == 1.0:
            assert u >= 0.7, f"Expected high u (MATLAB=1.0), got {u}"
        if expected_l == 1.0:
            assert l >= 0.5, f"Expected high l (MATLAB=1.0), got {l}"

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_bsds_parity_separate_fixture_files(
        self, bootstrap_fixture_dir
    ):
        """Verify behaviour using separately stored fixture files.

        Fixtures: bsds_bsds_bench.npy, bsds_bsds_models.npy,
                  bsds_bsds_c.npy, bsds_bsds_u.npy, bsds_bsds_l.npy
        """
        bench_path = bootstrap_fixture_dir / "bsds_bsds_bench.npy"
        models_path = bootstrap_fixture_dir / "bsds_bsds_models.npy"
        c_path = bootstrap_fixture_dir / "bsds_bsds_c.npy"
        u_path = bootstrap_fixture_dir / "bsds_bsds_u.npy"
        l_path = bootstrap_fixture_dir / "bsds_bsds_l.npy"

        # Skip if any fixture file is missing
        for p in [bench_path, models_path, c_path, u_path, l_path]:
            if not p.exists():
                pytest.skip(f"Fixture file not found: {p.name}")

        bench = np.load(bench_path, allow_pickle=True)
        models = np.load(models_path, allow_pickle=True)
        expected_c = float(np.load(c_path, allow_pickle=True))
        expected_u = float(np.load(u_path, allow_pickle=True))
        expected_l = float(np.load(l_path, allow_pickle=True))

        # Use parameters from bsds.csv: B=100, w=12, STUDENTIZED, STATIONARY
        c, u, l = bsds(bench, models, B=100, w=12,
                        type_="STUDENTIZED", boot="STATIONARY")

        # Hard checks: p-values must be valid
        assert 0.0 <= c <= 1.0, f"c={c} out of range"
        assert 0.0 <= u <= 1.0, f"u={u} out of range"
        assert 0.0 <= l <= 1.0, f"l={l} out of range"
        assert l <= c + 1e-10, f"l={l} should be <= c={c}"
        assert c <= u + 1e-10, f"c={c} should be <= u={u}"

        # Soft parity check with wider tolerance
        npt.assert_allclose(
            c, expected_c, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Consistent p-val soft parity (separate fixtures)",
        )
        npt.assert_allclose(
            u, expected_u, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Upper p-val soft parity (separate fixtures)",
        )
        npt.assert_allclose(
            l, expected_l, atol=BOOTSTRAP_PVAL_ATOL,
            err_msg="Lower p-val soft parity (separate fixtures)",
        )

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_bsds_parity_input_data_shapes(self, bootstrap_fixture_dir):
        """Verify that MATLAB fixture input data can be consumed by bsds
        without shape errors.  Validates that the numpy array shapes produced
        by scipy.io.loadmat / fixture conversion are correct for the Python
        implementation.
        """
        fixture_path = bootstrap_fixture_dir / "bsds.npy"
        if not fixture_path.exists():
            pytest.skip("Fixture file not found: bsds.npy")

        fixture = np.load(fixture_path, allow_pickle=True).item()

        for tc_prefix in ["tc1", "tc2", "tc3"]:
            bench = fixture[f"{tc_prefix}_bench"]
            models = fixture[f"{tc_prefix}_models"]
            B = int(fixture[f"{tc_prefix}_B"])
            w = int(fixture[f"{tc_prefix}_w"])
            type_ = fixture[f"{tc_prefix}_type"]
            boot = fixture[f"{tc_prefix}_boot"]

            # Verify shapes are compatible
            assert bench.ndim == 1, f"{tc_prefix}: bench should be 1-D"
            assert models.ndim == 2, f"{tc_prefix}: models should be 2-D"
            assert bench.shape[0] == models.shape[0], (
                f"{tc_prefix}: bench and models T mismatch"
            )

            # Execute without error
            c, u, l = bsds(bench, models, B=B, w=w, type_=type_, boot=boot)
            assert 0.0 <= c <= 1.0
            assert 0.0 <= u <= 1.0
            assert 0.0 <= l <= 1.0


# =========================================================================
# Edge Case Tests
# =========================================================================

class TestBsdsEdgeCases:
    """Edge case tests for bsds boundary conditions."""

    def test_bsds_large_w_relative_to_T(self, rng_local):
        """w close to T (T=50, w=25) should still produce valid results."""
        T = 50
        K = 3
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, K)) ** 2
        c, u, l = bsds(bench, models, B=50, w=25)
        assert 0.0 <= c <= 1.0, f"c={c} out of range"
        assert 0.0 <= u <= 1.0, f"u={u} out of range"
        assert 0.0 <= l <= 1.0, f"l={l} out of range"

    def test_bsds_w_equals_1(self, rng_local):
        """w=1 (independent bootstrap, degenerate blocks) should work.

        With block length 1, the block bootstrap degenerates to an i.i.d.
        bootstrap.
        """
        T = 100
        K = 3
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, K)) ** 2
        c, u, l = bsds(bench, models, B=50, w=1)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_many_models(self, rng_local):
        """K=50 models (stress test for variance computation)."""
        T = 100
        K = 50
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, K)) ** 2
        c, u, l = bsds(bench, models, B=50, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_identical_losses(self, rng_local):
        """When bench == models[:, 0] (zero differential for one model).

        Having one model with identical losses to the benchmark should still
        produce valid p-values.
        """
        T = 100
        K = 3
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, K)) ** 2
        # Make first model identical to benchmark
        models[:, 0] = bench.copy()
        c, u, l = bsds(bench, models, B=50, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_B_equals_1(self, rng_local):
        """B=1 (single bootstrap replication) should not crash.

        With only one replication the p-values will be 0.0 or 1.0.
        """
        T = 50
        K = 2
        bench = rng_local.standard_normal(T) ** 2
        models = rng_local.standard_normal((T, K)) ** 2
        c, u, l = bsds(bench, models, B=1, w=5)
        assert c in (0.0, 1.0), f"With B=1, c should be 0 or 1, got {c}"
        assert u in (0.0, 1.0), f"With B=1, u should be 0 or 1, got {u}"
        assert l in (0.0, 1.0), f"With B=1, l should be 0 or 1, got {l}"

    def test_bsds_minimum_valid_inputs(self, rng_local):
        """Minimum valid inputs: T=2, K=1, B=1, w=1."""
        bench = rng_local.standard_normal(2) ** 2
        models = rng_local.standard_normal((2, 1)) ** 2
        c, u, l = bsds(bench, models, B=1, w=1)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_type_empty_string_defaults_to_studentized(self, loss_data):
        """Empty string for type_ should default to STUDENTIZED.

        Ref: bsds.m:66-68 — if isempty(type) type = 'STUDENTIZED';
        Ref: bsds.py:135 — if type_ is None or type_ == '': ...
        """
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=50, w=5, type_="")
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_type_none_defaults_to_studentized(self, loss_data):
        """None for type_ should default to STUDENTIZED.

        Ref: bsds.py:135 — if type_ is None or type_ == '': ...
        """
        bench, models = loss_data
        c, u, l = bsds(bench, models, B=50, w=5, type_=None)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_all_zeros_bench(self, rng_local):
        """All-zero benchmark losses should still produce valid results."""
        T = 50
        K = 3
        bench = np.zeros(T)
        models = rng_local.standard_normal((T, K)) ** 2
        c, u, l = bsds(bench, models, B=50, w=5)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0

    def test_bsds_negate_for_goods(self, rng_local):
        """Negating bench and models for 'goods' (returns) should work.

        Ref: bsds.m:30-31 — 'If the quantities of interest are goods ...
        call bsds with -1*BENCH and -1*MODELS'
        """
        T = 200
        K = 3
        bench_good = 0.01 + rng_local.standard_normal(T)  # returns
        models_good = rng_local.standard_normal((T, K))
        c, u, l = bsds(-bench_good, -models_good, B=100, w=10)
        assert 0.0 <= c <= 1.0
        assert 0.0 <= u <= 1.0
        assert 0.0 <= l <= 1.0
