"""
Pytest tests for mfe_toolbox.utility.covvar — VAR-based long-run covariance estimation.

Tests the Python migration of ``utility/covvar.m`` (Den Haan & Levin, 1996).
The ``covvar`` function estimates the long-run covariance matrix of a T×K data
matrix using a VAR-based approach with information criterion-based lag
selection.  Five estimation methods are supported:

    1. Fixed lags 1..maxlag
    2. SIC-selected lag (default)
    3. AIC-selected lag
    4. SIC global search
    5. AIC global search

Every test validates output shapes, symmetry, lag selection behaviour, error
handling, and numerical parity against MATLAB/Octave reference fixtures
(atol=1e-6, rtol=1e-4 per AAP Section 0.7.1).

Fixtures loaded from ``tests/fixtures/utility/covvar.npy`` contain 10 test
cases generated by Octave 8.4.0 using the original ``utility/covvar.m``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import numpy.testing as npt
import pytest

from mfe_toolbox.utility.covvar import covvar

# Import tolerance constants and helpers from root conftest (auto-injected)
from tests.conftest import ATOL, RTOL, assert_allclose, load_fixture_npy


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


def _expected_default_maxlag(T: int, K: int) -> int:
    """Compute the expected default maxlag per covvar.m:39.

    Formula: min(floor(T / K), floor(1.2 * T^(1/3)))
    """
    return int(min(np.floor(T / K), np.floor(1.2 * T ** (1.0 / 3.0))))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def iid_data_3col(rng: np.random.Generator) -> np.ndarray:
    """Generate reproducible i.i.d. T=200, K=3 data for non-fixture tests.

    Uses a local RNG derived from the session-scoped ``rng`` fixture to
    ensure reproducibility while avoiding state mutation across tests.
    """
    local_rng = np.random.default_rng(12345)
    return local_rng.standard_normal((200, 3))


@pytest.fixture
def iid_data_1col(rng: np.random.Generator) -> np.ndarray:
    """Generate reproducible i.i.d. T=200, K=1 column vector."""
    local_rng = np.random.default_rng(67890)
    return local_rng.standard_normal((200, 1))


@pytest.fixture
def autocorr_data(rng: np.random.Generator) -> np.ndarray:
    """Generate T=300, K=2 data with VAR(1) autocorrelation for lag tests.

    Uses a simple AR(1) structure:  x_{t} = 0.6 * x_{t-1} + eps_{t}
    to ensure the lag selection methods find meaningful lags.
    """
    local_rng = np.random.default_rng(54321)
    T, K = 300, 2
    data = np.zeros((T, K))
    for t in range(1, T):
        data[t] = 0.6 * data[t - 1] + local_rng.standard_normal(K)
    return data


@pytest.fixture
def fixture_data(utility_fixture_dir: Path) -> dict:
    """Load the full covvar fixture dictionary from tests/fixtures/utility/.

    Each entry is keyed as 'test_case_N' and contains:
      - data : np.ndarray  (T×K input)
      - maxlag : int or None
      - method : int
      - expected_V : np.ndarray (K×K)
      - expected_lags : np.ndarray (1-D)

    The .npy file stores a 0-D object array wrapping a dict; ``.item()``
    extracts the Python dict.
    """
    raw = load_fixture_npy(utility_fixture_dir, "covvar")
    # load_fixture_npy returns np.ndarray; for 0-D object arrays, extract dict
    if isinstance(raw, np.ndarray) and raw.ndim == 0:
        return raw.item()
    return raw


# ---------------------------------------------------------------------------
# 1. test_covvar_default_method — Default is method=2 (SIC)
# ---------------------------------------------------------------------------


class TestCovvarDefaultMethod:
    """Calling covvar(data) without method argument uses method=2 (SIC)."""

    def test_covvar_default_method(self, iid_data_3col: np.ndarray) -> None:
        """Verify default call equals explicit method=2 call."""
        V_default, lags_default = covvar(iid_data_3col)
        V_explicit, lags_explicit = covvar(iid_data_3col, method=2)

        npt.assert_allclose(V_default, V_explicit, atol=ATOL, rtol=RTOL)
        npt.assert_array_equal(lags_default, lags_explicit)


# ---------------------------------------------------------------------------
# 2. test_covvar_method1 — Fixed lags
# ---------------------------------------------------------------------------


class TestCovvarMethod1:
    """Method 1: use lags 1..maxlag (fixed, no selection)."""

    def test_covvar_method1(self, iid_data_3col: np.ndarray) -> None:
        """Method=1 with maxlag=3 returns lagsused = [1, 2, 3]."""
        maxlag = 3
        V, lags = covvar(iid_data_3col, maxlag=maxlag, method=1)

        # Verify output shape
        K = iid_data_3col.shape[1]
        assert V.shape == (K, K), f"Expected ({K}, {K}), got {V.shape}"

        # Method 1 always uses ALL lags from 1 to maxlag
        # Ref: covvar.m:71 — indices{1}=1:maxlag
        expected_lags = np.arange(1, maxlag + 1, dtype=np.int64)
        npt.assert_array_equal(lags, expected_lags)


# ---------------------------------------------------------------------------
# 3. test_covvar_method2_sic — SIC selection
# ---------------------------------------------------------------------------


class TestCovvarMethod2SIC:
    """Method 2: SIC-based lag selection (sequential)."""

    def test_covvar_method2_sic(self, iid_data_3col: np.ndarray) -> None:
        """Method=2 selects lags via SIC; output is K×K and symmetric."""
        V, lags = covvar(iid_data_3col, maxlag=5, method=2)

        K = iid_data_3col.shape[1]
        assert V.shape == (K, K)
        # Output covariance must be symmetric
        npt.assert_allclose(V, V.T, atol=1e-12)
        # lags must be 1-D integer array
        assert lags.ndim == 1
        assert lags.dtype in (np.int64, np.int32, int)


# ---------------------------------------------------------------------------
# 4. test_covvar_method3_aic — AIC selection
# ---------------------------------------------------------------------------


class TestCovvarMethod3AIC:
    """Method 3: AIC-based lag selection (sequential)."""

    def test_covvar_method3_aic(self, iid_data_3col: np.ndarray) -> None:
        """Method=3 selects lags via AIC; output is K×K and symmetric."""
        V, lags = covvar(iid_data_3col, maxlag=5, method=3)

        K = iid_data_3col.shape[1]
        assert V.shape == (K, K)
        npt.assert_allclose(V, V.T, atol=1e-12)
        assert lags.ndim == 1


# ---------------------------------------------------------------------------
# 5. test_covvar_output_shape — Various T, K combinations
# ---------------------------------------------------------------------------


class TestCovvarOutputShape:
    """Verify the V output is always K×K for various data dimensions."""

    @pytest.mark.parametrize("T,K", [(100, 2), (200, 3), (500, 4), (300, 1)])
    def test_covvar_output_shape(self, T: int, K: int) -> None:
        """covvar(T×K data) → K×K covariance matrix."""
        local_rng = np.random.default_rng(99)
        data = local_rng.standard_normal((T, K))
        V, lags = covvar(data)

        assert V.shape == (K, K), (
            f"Expected V shape ({K}, {K}) for T={T}, K={K}; got {V.shape}"
        )
        assert isinstance(V, np.ndarray)


# ---------------------------------------------------------------------------
# 6. test_covvar_output_symmetric — V must equal V.T
# ---------------------------------------------------------------------------


class TestCovvarOutputSymmetric:
    """Long-run covariance matrix must always be symmetric."""

    @pytest.mark.parametrize("method", [1, 2, 3, 4, 5])
    def test_covvar_output_symmetric(self, method: int) -> None:
        """V is symmetric for all five methods."""
        local_rng = np.random.default_rng(42)
        data = local_rng.standard_normal((150, 2))
        maxlag = 3  # Keep small for method 4/5 global search feasibility
        V, _ = covvar(data, maxlag=maxlag, method=method)

        npt.assert_allclose(
            V, V.T, atol=1e-12,
            err_msg=f"V is not symmetric for method={method}",
        )


# ---------------------------------------------------------------------------
# 7. test_covvar_returns_lagsused — second return value is 1-D int array
# ---------------------------------------------------------------------------


class TestCovvarReturnsLagsused:
    """Second return value must be a 1-D integer array of lag indices."""

    def test_covvar_returns_lagsused(self, iid_data_3col: np.ndarray) -> None:
        """lagsused is a 1-D ndarray with integer dtype."""
        _, lags = covvar(iid_data_3col, maxlag=5, method=2)

        assert isinstance(lags, np.ndarray), "lagsused must be np.ndarray"
        assert lags.ndim == 1, f"lagsused must be 1-D, got {lags.ndim}"
        assert np.issubdtype(lags.dtype, np.integer), (
            f"lagsused dtype must be integer, got {lags.dtype}"
        )

    def test_covvar_returns_lagsused_method1(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """Method=1 lagsused contains all lags from 1 to maxlag."""
        maxlag = 4
        _, lags = covvar(iid_data_3col, maxlag=maxlag, method=1)
        expected = np.arange(1, maxlag + 1, dtype=np.int64)
        npt.assert_array_equal(lags, expected)


# ---------------------------------------------------------------------------
# 8. test_covvar_default_maxlag — Verify default formula
# ---------------------------------------------------------------------------


class TestCovvarDefaultMaxlag:
    """Default maxlag must equal min(floor(T/K), floor(1.2*T^(1/3)))."""

    @pytest.mark.parametrize("T,K", [(100, 2), (200, 3), (500, 4), (1000, 5)])
    def test_covvar_default_maxlag(self, T: int, K: int) -> None:
        """Method=1 with default maxlag uses all lags up to the formula result.

        Since method=1 always uses all lags 1..maxlag, the lagsused length
        equals the default maxlag computed internally.
        """
        local_rng = np.random.default_rng(111)
        data = local_rng.standard_normal((T, K))

        # Call with method=1 so lagsused = [1, 2, ..., maxlag_default]
        _, lags = covvar(data, method=1)

        expected_maxlag = _expected_default_maxlag(T, K)
        if expected_maxlag > 0:
            assert len(lags) == expected_maxlag, (
                f"For T={T}, K={K}: expected maxlag={expected_maxlag}, "
                f"got lagsused length={len(lags)}"
            )
            # Verify it's consecutive 1..maxlag
            npt.assert_array_equal(
                lags, np.arange(1, expected_maxlag + 1, dtype=np.int64)
            )


# ---------------------------------------------------------------------------
# 9. test_covvar_custom_maxlag — Explicit maxlag
# ---------------------------------------------------------------------------


class TestCovvarCustomMaxlag:
    """Custom maxlag overrides the default formula."""

    def test_covvar_custom_maxlag(self, iid_data_3col: np.ndarray) -> None:
        """Explicit maxlag=3 with method=1 gives lags [1, 2, 3]."""
        V, lags = covvar(iid_data_3col, maxlag=3, method=1)
        npt.assert_array_equal(lags, np.array([1, 2, 3], dtype=np.int64))

    def test_covvar_custom_maxlag_changes_result(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """Different maxlag values produce different fixed-lag results."""
        V3, lags3 = covvar(iid_data_3col, maxlag=3, method=1)
        V5, lags5 = covvar(iid_data_3col, maxlag=5, method=1)

        # Different maxlag should give different V matrices (with fixed method=1)
        assert not np.allclose(V3, V5, atol=1e-10), (
            "Different maxlag with method=1 should generally yield different V"
        )
        assert len(lags3) == 3
        assert len(lags5) == 5


# ---------------------------------------------------------------------------
# 10. test_covvar_single_column — K=1 produces 1×1 output
# ---------------------------------------------------------------------------


class TestCovvarSingleColumn:
    """Single-column (K=1) data produces a 1×1 covariance matrix."""

    def test_covvar_single_column(self, iid_data_1col: np.ndarray) -> None:
        """K=1 → V has shape (1, 1)."""
        V, lags = covvar(iid_data_1col, maxlag=5, method=2)

        assert V.shape == (1, 1), f"Expected (1, 1), got {V.shape}"
        # Scalar variance must be positive
        assert V[0, 0] > 0, "Variance of non-zero data must be positive"

    def test_covvar_single_column_1d_input(self) -> None:
        """1-D input array is reshaped to (T, 1) and treated as K=1."""
        local_rng = np.random.default_rng(333)
        data_1d = local_rng.standard_normal(200)
        V, lags = covvar(data_1d, maxlag=5, method=2)

        assert V.shape == (1, 1), f"Expected (1, 1) for 1-D input, got {V.shape}"
        assert V[0, 0] > 0


# ---------------------------------------------------------------------------
# 11. test_covvar_iid_data — i.i.d. should select few/no lags
# ---------------------------------------------------------------------------


class TestCovvarIIDData:
    """For i.i.d. data the information criteria should prefer no/few lags."""

    def test_covvar_iid_data(self) -> None:
        """SIC-selected (method=2) lags on large i.i.d. data selects few/no lags.

        With i.i.d. draws, adding lags increases the IC penalty without
        improving fit, so the optimal lag set is typically empty.
        """
        local_rng = np.random.default_rng(9999)
        data = local_rng.standard_normal((500, 3))
        V, lags = covvar(data, maxlag=5, method=2)

        # For large i.i.d. sample, SIC should select 0 lags (empty lags)
        # or at most 1-2 lags by chance. We accept up to 2 as margin.
        assert len(lags) <= 2, (
            f"Expected ≤2 lags for i.i.d. data with SIC, got {len(lags)}: {lags}"
        )

    def test_covvar_iid_aic(self) -> None:
        """AIC-selected (method=3) on i.i.d. data also selects few/no lags."""
        local_rng = np.random.default_rng(8888)
        data = local_rng.standard_normal((500, 3))
        V, lags = covvar(data, maxlag=5, method=3)

        # AIC tends to be more liberal than SIC but still should be small
        assert len(lags) <= 3, (
            f"Expected ≤3 lags for i.i.d. data with AIC, got {len(lags)}: {lags}"
        )


# ---------------------------------------------------------------------------
# 12. test_covvar_invalid_method_raises — Error handling
# ---------------------------------------------------------------------------


class TestCovvarInvalidMethodRaises:
    """Invalid method or maxlag values must raise ValueError."""

    def test_covvar_invalid_method_raises(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """method=6 raises ValueError."""
        with pytest.raises(ValueError, match="METHOD must be a scalar"):
            covvar(iid_data_3col, method=6)

    def test_covvar_method_zero_raises(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """method=0 raises ValueError."""
        with pytest.raises(ValueError, match="METHOD must be a scalar"):
            covvar(iid_data_3col, method=0)

    def test_covvar_method_negative_raises(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """method=-1 raises ValueError."""
        with pytest.raises(ValueError, match="METHOD must be a scalar"):
            covvar(iid_data_3col, method=-1)

    def test_covvar_negative_maxlag_raises(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """Negative maxlag raises ValueError."""
        with pytest.raises(ValueError, match="MAXLAG must be a non-negative"):
            covvar(iid_data_3col, maxlag=-1, method=2)

    def test_covvar_maxlag_exceeds_limit_raises(
        self, iid_data_3col: np.ndarray
    ) -> None:
        """maxlag > floor(T/K) raises ValueError."""
        T, K = iid_data_3col.shape
        too_large = int(np.floor(T / K)) + 1
        with pytest.raises(ValueError, match="MAXLAG must be a non-negative"):
            covvar(iid_data_3col, maxlag=too_large, method=2)

    def test_covvar_3d_data_raises(self) -> None:
        """3-D data array raises ValueError."""
        data_3d = np.zeros((10, 3, 2))
        with pytest.raises(ValueError, match="DATA must be a T by K matrix"):
            covvar(data_3d)


# ---------------------------------------------------------------------------
# 13. test_covvar_fixture_parity — MATLAB fixture comparison
# ---------------------------------------------------------------------------


class TestCovvarFixtureParity:
    """Numerical parity against MATLAB/Octave reference fixtures.

    Fixtures are loaded from ``tests/fixtures/utility/covvar.npy`` which
    contains 10 test cases generated by Octave 8.4.0 with the original
    ``utility/covvar.m``.

    Per AAP Section 0.7.1: atol=1e-6, rtol=1e-4 are HARD requirements.
    """

    @pytest.mark.parametrize(
        "case_key",
        [
            "test_case_1",
            "test_case_2",
            "test_case_3",
            "test_case_4",
            "test_case_5",
            "test_case_6",
            "test_case_7",
            "test_case_8",
            "test_case_9",
            "test_case_10",
        ],
    )
    def test_covvar_fixture_parity(
        self, fixture_data: dict, case_key: str
    ) -> None:
        """Compare covvar output to MATLAB reference for each fixture case."""
        case = fixture_data[case_key]
        data = case["data"]
        maxlag = case["maxlag"]
        method = case["method"]
        expected_V = case["expected_V"]
        expected_lags = case["expected_lags"]

        # Call the Python implementation
        # maxlag=None in fixture means use default
        if maxlag is None:
            V, lags = covvar(data, method=method)
        else:
            V, lags = covvar(data, maxlag=int(maxlag), method=int(method))

        # Verify covariance matrix parity (atol=1e-6, rtol=1e-4)
        assert_allclose(
            V, expected_V,
            err_msg=(
                f"Covariance matrix mismatch for {case_key} "
                f"(method={method}, maxlag={maxlag})"
            ),
        )

        # Verify lag selection parity
        # expected_lags from MATLAB may be float; convert to int for comparison
        if len(expected_lags) > 0:
            expected_lags_int = np.array(expected_lags, dtype=np.int64)
        else:
            expected_lags_int = np.array([], dtype=np.int64)

        npt.assert_array_equal(
            lags, expected_lags_int,
            err_msg=(
                f"Lag selection mismatch for {case_key}: "
                f"got {lags}, expected {expected_lags_int}"
            ),
        )

    def test_covvar_fixture_covvar_out_properties(
        self, utility_fixture_dir: Path
    ) -> None:
        """Verify the standalone covvar_covvar_out.npy fixture has valid structure.

        This fixture contains a K×K covariance matrix output from covvar().
        Since the input data used to generate this standalone fixture is not
        bundled with the fixture, we verify structural properties: shape,
        symmetry, positive semi-definiteness, and reasonable magnitudes.
        """
        expected_V = load_fixture_npy(utility_fixture_dir, "covvar_covvar_out")

        # Must be a 2-D square matrix
        assert expected_V.ndim == 2, f"Expected 2-D, got {expected_V.ndim}-D"
        K = expected_V.shape[0]
        assert expected_V.shape == (K, K), (
            f"Expected square matrix, got {expected_V.shape}"
        )

        # Must be symmetric (covariance matrices are symmetric)
        npt.assert_allclose(
            expected_V, expected_V.T, atol=1e-12,
            err_msg="covvar_covvar_out fixture is not symmetric",
        )

        # Eigenvalues should be non-negative (positive semi-definite)
        eigenvalues = np.linalg.eigvalsh(expected_V)
        assert np.all(eigenvalues >= -1e-10), (
            f"Fixture covariance has negative eigenvalues: {eigenvalues}"
        )


# ---------------------------------------------------------------------------
# Additional edge case / method coverage tests
# ---------------------------------------------------------------------------


class TestCovvarGlobalSearch:
    """Tests specifically for global search methods (4 and 5)."""

    def test_covvar_method4_global_sic(self) -> None:
        """Method=4 (global SIC) produces valid KxK symmetric output."""
        local_rng = np.random.default_rng(777)
        data = local_rng.standard_normal((150, 2))
        V, lags = covvar(data, maxlag=3, method=4)

        assert V.shape == (2, 2)
        npt.assert_allclose(V, V.T, atol=1e-12)
        assert isinstance(lags, np.ndarray)
        assert lags.ndim == 1

    def test_covvar_method5_global_aic(self) -> None:
        """Method=5 (global AIC) produces valid KxK symmetric output."""
        local_rng = np.random.default_rng(888)
        data = local_rng.standard_normal((150, 2))
        V, lags = covvar(data, maxlag=3, method=5)

        assert V.shape == (2, 2)
        npt.assert_allclose(V, V.T, atol=1e-12)
        assert isinstance(lags, np.ndarray)
        assert lags.ndim == 1

    def test_covvar_method4_lags_subset(self) -> None:
        """Method=4 may select non-consecutive lags (subset search)."""
        # Autocorrelated data to encourage lag selection
        local_rng = np.random.default_rng(1111)
        T, K = 200, 2
        data = np.zeros((T, K))
        for t in range(1, T):
            data[t] = 0.5 * data[t - 1] + local_rng.standard_normal(K)

        V, lags = covvar(data, maxlag=3, method=4)

        # Lags must be a subset of {1, 2, 3} or empty
        if len(lags) > 0:
            assert all(lag in (1, 2, 3) for lag in lags), (
                f"Lags {lags} contain values outside {{1, 2, 3}}"
            )


class TestCovvarMaxlagZero:
    """Edge case: maxlag=0 means no lags, covariance is standard cov."""

    def test_covvar_maxlag_zero(self) -> None:
        """maxlag=0 with any method returns standard covariance."""
        local_rng = np.random.default_rng(555)
        data = local_rng.standard_normal((200, 3))
        V, lags = covvar(data, maxlag=0, method=1)

        # With maxlag=0, lagsused should be empty
        assert len(lags) == 0, f"Expected empty lags for maxlag=0, got {lags}"

        # V should equal population covariance (T-1)/T * cov
        T = data.shape[0]
        expected_cov = np.cov(data, rowvar=False) * ((T - 1) / T)
        npt.assert_allclose(V, expected_cov, atol=1e-10)
