"""Pytest tests for mfe_toolbox.utility.x2mdate — Excel serial date conversion.

Tests the :func:`~mfe_toolbox.utility.x2mdate.x2mdate` function which converts
Excel serial date numbers to ``pandas.Timestamp`` objects, supporting both the
Windows 1900 date system (type=0, base Dec 30, 1899) and the Mac 1904 date
system (type=1, base Jan 1, 1904).

Source reference: ``utility/x2mdate.m`` (80 lines, Kevin Sheppard)

Fixture reference: ``tests/fixtures/utility/x2mdate.npy`` — comprehensive
fixture generated by Octave 8.4.0 containing Excel date arrays, expected
MATLAB datenums, and human-readable date strings for both date systems.
"""

import datetime
from pathlib import Path

import numpy as np
import numpy.testing as npt
import pandas as pd
import pytest

from mfe_toolbox.utility.x2mdate import x2mdate


# ---------------------------------------------------------------------------
# Test 1: Known date conversions from MATLAB docstring
# ---------------------------------------------------------------------------
# Ref: x2mdate.m:18-23 — Expected dates from docstring examples:
#   XLSDATE = [35000 40000 41000]; datestr(x2mdate(XLSDATE))
#   → 28-Oct-1995, 06-Jul-2009, 01-Apr-2012
@pytest.mark.parametrize(
    "xldate, expected_year, expected_month, expected_day",
    [
        (35000, 1995, 10, 28),
        (40000, 2009, 7, 6),
        (41000, 2012, 4, 1),
    ],
    ids=["35000_oct1995", "40000_jul2009", "41000_apr2012"],
)
def test_x2mdate_known_dates(
    xldate: int,
    expected_year: int,
    expected_month: int,
    expected_day: int,
) -> None:
    """Verify known Excel serial dates produce correct calendar dates.

    Uses the docstring examples from x2mdate.m and cross-validates against
    the Octave-generated fixture ``date_strings_1900``.
    """
    result = x2mdate(np.array([xldate]))
    actual_ts: pd.Timestamp = result.flat[0]
    expected_date = datetime.date(expected_year, expected_month, expected_day)
    assert actual_ts.date() == expected_date, (
        f"xldate={xldate}: expected {expected_date}, got {actual_ts.date()}"
    )


# ---------------------------------------------------------------------------
# Test 2: Vector input
# ---------------------------------------------------------------------------
def test_x2mdate_vector() -> None:
    """Verify x2mdate handles an array of Excel dates → array of timestamps.

    Ref: x2mdate.m:77 — mldate=zeros(size(xlsdate));
    Output must have the same shape as the input array.
    """
    xl_dates = np.array([35000, 40000, 41000])
    result = x2mdate(xl_dates)

    # Result shape must match input shape
    assert isinstance(result, np.ndarray), (
        f"Expected np.ndarray, got {type(result)}"
    )
    assert result.shape == xl_dates.shape, (
        f"Shape mismatch: expected {xl_dates.shape}, got {result.shape}"
    )

    # Verify each date component
    expected_dates = [
        datetime.date(1995, 10, 28),
        datetime.date(2009, 7, 6),
        datetime.date(2012, 4, 1),
    ]
    for i, expected_date in enumerate(expected_dates):
        actual_ts: pd.Timestamp = result[i]
        assert actual_ts.date() == expected_date, (
            f"Index {i}: expected {expected_date}, got {actual_ts.date()}"
        )


# ---------------------------------------------------------------------------
# Test 3: Default type=0 (Windows base)
# ---------------------------------------------------------------------------
def test_x2mdate_type0_default() -> None:
    """Verify default date_type=0 uses Windows Excel base date (Dec 30, 1899).

    Ref: x2mdate.m:40-42 — Default type=0 when nargin==1.
    Calling without explicit date_type must produce the same result as
    calling with date_type=0.
    """
    xl_date = np.array([35000])

    # Call with explicit type=0
    result_explicit = x2mdate(xl_date, date_type=0)
    # Call with default (no type argument)
    result_default = x2mdate(xl_date)

    # Both must produce identical results
    assert result_explicit.flat[0] == result_default.flat[0], (
        f"Explicit type=0 gave {result_explicit.flat[0]}, "
        f"default gave {result_default.flat[0]}"
    )
    # Verify the date matches the known docstring value
    assert result_default.flat[0].date() == datetime.date(1995, 10, 28)


# ---------------------------------------------------------------------------
# Test 4: Type 1 (Mac base)
# ---------------------------------------------------------------------------
def test_x2mdate_type1_mac() -> None:
    """Verify date_type=1 uses Mac Excel base date (Jan 1, 1904).

    Ref: x2mdate.m:79 — mldate(type) = xlsdate(type) + datenum('1-Jan-1904')
    With xldate=0 and type=1, the result should be exactly Jan 1, 1904.
    """
    # xldate=0 with type=1: base_date_1 + 0 days = Jan 1, 1904
    result_zero = x2mdate(np.array([0]), date_type=1)
    assert result_zero.flat[0].date() == datetime.date(1904, 1, 1), (
        f"xldate=0 type=1: expected 1904-01-01, got {result_zero.flat[0]}"
    )

    # xldate=1 with type=1: Jan 1, 1904 + 1 day = Jan 2, 1904
    # Ref: Octave fixture date_strings_1904[1] = '02-Jan-1904'
    result_one = x2mdate(np.array([1]), date_type=1)
    assert result_one.flat[0].date() == datetime.date(1904, 1, 2), (
        f"xldate=1 type=1: expected 1904-01-02, got {result_one.flat[0]}"
    )


# ---------------------------------------------------------------------------
# Test 5: Type 0 vs Type 1 offset
# ---------------------------------------------------------------------------
def test_x2mdate_type0_vs_type1() -> None:
    """Verify the offset between type 0 and type 1 is exactly 1462 days.

    Ref: x2mdate.m:78-79 — The difference between the two base dates is:
        datenum('1-Jan-1904') - datenum('30-Dec-1899') = 695422 - 693960 = 1462
    For the same Excel serial number, type 1 produces a date 1462 days later.
    """
    xl_date = np.array([35000])
    result_type0 = x2mdate(xl_date, date_type=0)
    result_type1 = x2mdate(xl_date, date_type=1)

    ts_type0: pd.Timestamp = result_type0.flat[0]
    ts_type1: pd.Timestamp = result_type1.flat[0]

    # Verify using pd.Timedelta
    delta_pd = ts_type1 - ts_type0
    assert delta_pd == pd.Timedelta(days=1462), (
        f"Expected 1462-day offset, got {delta_pd}"
    )

    # Also verify using datetime.timedelta
    assert delta_pd == datetime.timedelta(days=1462)

    # Type 1 must always be later than type 0 for the same serial number
    assert ts_type1 > ts_type0


# ---------------------------------------------------------------------------
# Test 6: Excel day 1
# ---------------------------------------------------------------------------
def test_x2mdate_excel_day1() -> None:
    """Verify xldate=1 with type=0 produces Dec 31, 1899.

    Ref: x2mdate.m:78 — mldate = xlsdate + datenum('30-Dec-1899')
    With base date Dec 30, 1899: xldate=1 → Dec 30, 1899 + 1 day = Dec 31, 1899.

    Note: In the real Windows Excel system, serial 1 = Jan 1, 1900.
    The MATLAB function uses Dec 30 as the base (not Dec 31), resulting in
    an offset. This matches the Octave fixture: date_strings_1900[1] = '31-Dec-1899'.
    """
    xl_date = np.array([1])
    result = x2mdate(xl_date, date_type=0)
    actual_ts: pd.Timestamp = result.flat[0]

    # Ref: Octave fixture confirms: xldate=1 → '31-Dec-1899'
    expected = datetime.date(1899, 12, 31)
    assert actual_ts.date() == expected, (
        f"xldate=1 type=0: expected {expected}, got {actual_ts.date()}"
    )

    # Also verify xldate=2 → Jan 1, 1900
    # Ref: Octave fixture date_strings_1900[2] = '01-Jan-1900'
    result_2 = x2mdate(np.array([2]), date_type=0)
    assert result_2.flat[0].date() == datetime.date(1900, 1, 1)


# ---------------------------------------------------------------------------
# Test 7: Non-numeric input raises
# ---------------------------------------------------------------------------
def test_x2mdate_non_numeric_raises() -> None:
    """Verify string input raises ValueError.

    Ref: x2mdate.m:44-46 — if any(ischar(xlsdate)) error('XLSDATE must be numeric')
    """
    with pytest.raises(ValueError, match="XLSDATE must be numeric"):
        x2mdate("not_a_number")

    # Also test with a non-numeric numpy array
    with pytest.raises(ValueError, match="XLSDATE must be numeric"):
        x2mdate(np.array(["a", "b", "c"]))


# ---------------------------------------------------------------------------
# Test 8: Invalid type raises
# ---------------------------------------------------------------------------
def test_x2mdate_invalid_type_raises() -> None:
    """Verify invalid date_type values raise ValueError.

    Ref: x2mdate.m:64-66 — if any(~ismember(type,[0 1]))
        error('TYPE must be either 0 or 1.')
    """
    with pytest.raises(ValueError, match="TYPE must be either 0 or 1"):
        x2mdate(np.array([35000]), date_type=2)

    with pytest.raises(ValueError, match="TYPE must be either 0 or 1"):
        x2mdate(np.array([35000]), date_type=-1)

    with pytest.raises(ValueError, match="TYPE must be either 0 or 1"):
        x2mdate(np.array([35000]), date_type=3)


# ---------------------------------------------------------------------------
# Test 9: Output type verification
# ---------------------------------------------------------------------------
def test_x2mdate_output_type() -> None:
    """Verify x2mdate returns np.ndarray containing pd.Timestamp objects.

    Ref: x2mdate.py docstring — Returns numpy.ndarray of pd.Timestamp
    objects with dtype=object, same shape as input.
    """
    # Array input
    xl_dates = np.array([35000, 40000])
    result = x2mdate(xl_dates)
    assert isinstance(result, np.ndarray), (
        f"Expected np.ndarray, got {type(result)}"
    )
    assert result.dtype == object, (
        f"Expected object dtype for Timestamp array, got {result.dtype}"
    )
    for elem in result.flat:
        assert isinstance(elem, pd.Timestamp), (
            f"Expected pd.Timestamp element, got {type(elem)}"
        )

    # Scalar input → 0-d ndarray
    result_scalar = x2mdate(35000)
    assert isinstance(result_scalar, np.ndarray), (
        f"Scalar input should return np.ndarray, got {type(result_scalar)}"
    )
    assert isinstance(result_scalar.flat[0], pd.Timestamp)


# ---------------------------------------------------------------------------
# Test 10: Fixture parity
# ---------------------------------------------------------------------------
def test_x2mdate_fixture_parity(utility_fixture_dir) -> None:
    """Compare x2mdate output against MATLAB/Octave-generated fixture data.

    Loads the comprehensive fixture from tests/fixtures/utility/x2mdate.npy
    which contains Excel dates, expected MATLAB datenums, and date strings
    for both the 1900 (type=0) and 1904 (type=1) date systems.

    Validates:
    1. Type 0 dates match fixture date_strings_1900
    2. Type 1 dates match fixture date_strings_1904
    3. Mixed-type vector test from fixture
    4. Numerical consistency of MATLAB datenum offsets
    """
    fixture_path = Path(utility_fixture_dir) / "x2mdate.npy"
    if not fixture_path.exists():
        pytest.skip(f"Fixture file not found: {fixture_path}")

    fixture = np.load(fixture_path, allow_pickle=True).item()

    # --- Type 0 (1900 system) date string verification ---
    excel_dates_1900 = fixture["excel_dates_1900"]
    date_strings_1900 = fixture["date_strings_1900"]
    expected_mldates_1900 = fixture["expected_mldates_1900"]
    base_datenum_1900 = fixture["base_datenum_1900"]  # 693960

    result_1900 = x2mdate(excel_dates_1900, date_type=0)

    for i, (ts, expected_str) in enumerate(
        zip(result_1900.flat, date_strings_1900)
    ):
        # Parse date part only (strip time component like ' 06:00')
        expected_date_str = expected_str.split(" ")[0]
        expected_dt = datetime.datetime.strptime(expected_date_str, "%d-%b-%Y")
        assert ts.date() == expected_dt.date(), (
            f"Type 0, index {i}: xldate={excel_dates_1900[i]}, "
            f"expected {expected_date_str}, got {ts.date()}"
        )

    # Verify MATLAB datenum arithmetic consistency:
    # MATLAB datenum = xlsdate + base_datenum_1900
    npt.assert_allclose(
        excel_dates_1900 + base_datenum_1900,
        expected_mldates_1900,
        atol=1e-6,
        rtol=1e-4,
        err_msg="Type 0 MATLAB datenum arithmetic consistency failure",
    )

    # --- Type 1 (1904 system) date string verification ---
    excel_dates_1904 = fixture["excel_dates_1904"]
    date_strings_1904 = fixture["date_strings_1904"]
    expected_mldates_1904 = fixture["expected_mldates_1904"]
    base_datenum_1904 = fixture["base_datenum_1904"]  # 695422

    result_1904 = x2mdate(excel_dates_1904, date_type=1)

    for i, (ts, expected_str) in enumerate(
        zip(result_1904.flat, date_strings_1904)
    ):
        expected_date_str = expected_str.split(" ")[0]
        expected_dt = datetime.datetime.strptime(expected_date_str, "%d-%b-%Y")
        assert ts.date() == expected_dt.date(), (
            f"Type 1, index {i}: xldate={excel_dates_1904[i]}, "
            f"expected {expected_date_str}, got {ts.date()}"
        )

    # Verify MATLAB datenum arithmetic consistency
    npt.assert_allclose(
        excel_dates_1904 + base_datenum_1904,
        expected_mldates_1904,
        atol=1e-6,
        rtol=1e-4,
        err_msg="Type 1 MATLAB datenum arithmetic consistency failure",
    )

    # --- Mixed type vector test ---
    mixed = fixture["mixed_type_test"]
    mixed_dates = mixed["excel_dates"]
    mixed_types = mixed["types"].astype(int)
    mixed_expected_mldates = mixed["expected_mldates"]

    mixed_result = x2mdate(mixed_dates, date_type=mixed_types)

    # Verify shape matches
    assert mixed_result.shape == mixed_dates.shape, (
        f"Mixed test shape: expected {mixed_dates.shape}, "
        f"got {mixed_result.shape}"
    )

    # Verify the per-element type selection works by checking that
    # type=0 entries differ from type=1 entries for the same Excel date.
    # mixed_dates = [35000, 35000, 40000, 40000]
    # mixed_types = [0, 1, 0, 1]
    # So indices 0 and 1 have the same xldate but different types.
    ts_35000_type0 = mixed_result[0]
    ts_35000_type1 = mixed_result[1]
    assert ts_35000_type1 - ts_35000_type0 == pd.Timedelta(days=1462), (
        f"Mixed type test: 35000 type1-type0 offset should be 1462 days, "
        f"got {ts_35000_type1 - ts_35000_type0}"
    )

    ts_40000_type0 = mixed_result[2]
    ts_40000_type1 = mixed_result[3]
    assert ts_40000_type1 - ts_40000_type0 == pd.Timedelta(days=1462), (
        f"Mixed type test: 40000 type1-type0 offset should be 1462 days, "
        f"got {ts_40000_type1 - ts_40000_type0}"
    )

    # --- Default type test from fixture ---
    default_test = fixture["default_type_test"]
    default_dates = default_test["excel_dates"]
    default_expected_mldates = default_test["expected_mldates"]

    default_result = x2mdate(default_dates)

    # Verify docstring example produces expected MATLAB datenums
    npt.assert_allclose(
        default_dates + base_datenum_1900,
        default_expected_mldates,
        atol=1e-6,
        rtol=1e-4,
        err_msg="Default type test MATLAB datenum parity failure",
    )
