"""Pytest parity tests for the Jarque-Bera normality test.

Verifies numerical parity (±1e-6 atol, ±1e-4 rtol) of the migrated
``mfe_toolbox.tests.jarquebera.jarquebera`` function against MATLAB
reference outputs generated by GNU Octave from ``tests/jarquebera.m``.

Per AAP Section 0.7.1 all migrated functions MUST pass
``numpy.testing.assert_allclose(actual, expected, atol=1e-6, rtol=1e-4)``
against MATLAB-generated fixtures.

Fixture data is loaded from ``tests/fixtures/tests/jarquebera.npy``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import numpy.testing as npt
import pytest
from scipy.stats import chi2

from mfe_toolbox.tests.jarquebera import jarquebera
from tests.conftest import ATOL, RTOL, assert_allclose, load_fixture_npy


# ---------------------------------------------------------------------------
# Phase 1: Unit Tests (no fixture dependency)
# ---------------------------------------------------------------------------


class TestJarqueberaNormalData:
    """Normal data should not reject normality (test_jarquebera_normal_data)."""

    def test_jarquebera_normal_data(self, rng: np.random.Generator) -> None:
        """Large normal samples should not reject normality at alpha=0.05."""
        data = rng.standard_normal(1000)
        statistic, pval, H = jarquebera(data)

        # For large normal samples, JB stat should be small
        assert isinstance(statistic, float)
        assert isinstance(pval, float)
        assert isinstance(H, bool)

        # Structural invariants
        assert statistic >= 0.0
        assert 0.0 <= pval <= 1.0

        # For N(0,1) with 1000 observations, should typically not reject
        # Ref: jarquebera.m:73 — H = pval < alpha
        assert H is False, (
            f"Normal data unexpectedly rejected at alpha=0.05 "
            f"(stat={statistic:.6f}, pval={pval:.6f})"
        )


class TestJarqueberaNonnormalData:
    """Non-normal data should reject normality (test_jarquebera_nonnormal_data)."""

    def test_jarquebera_nonnormal_data(self, rng: np.random.Generator) -> None:
        """Exponential (heavily skewed) data should reject normality."""
        data = rng.exponential(1.0, size=1000)
        statistic, pval, H = jarquebera(data)

        # Exponential data has skewness=2, excess kurtosis=6 — far from normal
        assert statistic > 0.0
        assert pval < 0.05
        assert H is True, (
            f"Exponential data failed to reject normality "
            f"(stat={statistic:.6f}, pval={pval:.6f})"
        )


class TestJarqueberaKParameter:
    """Different K values affect the statistic (test_jarquebera_K_parameter)."""

    @pytest.mark.parametrize("K", [0, 2, 5])
    def test_jarquebera_K_parameter(
        self, rng: np.random.Generator, K: int
    ) -> None:
        """Verify statistic = (T-K) * (...) so larger K reduces statistic.

        Ref: jarquebera.m:71 — ``statistic = (T-K)*(mean(z.^3)^2/6+(mean(z.^4)-3)^2/24)``
        """
        data = rng.standard_normal(100)
        statistic, pval, H = jarquebera(data, K=K)

        assert isinstance(statistic, float)
        assert statistic >= 0.0
        assert 0.0 <= pval <= 1.0

    def test_jarquebera_K_reduces_statistic(
        self, rng: np.random.Generator
    ) -> None:
        """Larger K strictly reduces the JB statistic for identical data."""
        # Use a fresh local rng to avoid consuming session rng state
        local_rng = np.random.default_rng(12345)
        data = local_rng.standard_normal(200)

        stat_k0, _, _ = jarquebera(data, K=0)
        stat_k2, _, _ = jarquebera(data, K=2)
        stat_k5, _, _ = jarquebera(data, K=5)

        # Since stat = (T-K)*factor, and factor is the same for all K,
        # stat_k0 > stat_k2 > stat_k5 (for T=200, factor > 0)
        assert stat_k0 > stat_k2, (
            f"K=0 stat ({stat_k0:.6f}) should exceed K=2 stat ({stat_k2:.6f})"
        )
        assert stat_k2 > stat_k5, (
            f"K=2 stat ({stat_k2:.6f}) should exceed K=5 stat ({stat_k5:.6f})"
        )


class TestJarqueberaAlphaVariations:
    """Alpha affects only H, not statistic or pval (test_jarquebera_alpha_variations)."""

    @pytest.mark.parametrize("alpha", [0.01, 0.05, 0.10])
    def test_jarquebera_alpha_stat_pval_unchanged(
        self, rng: np.random.Generator, alpha: float
    ) -> None:
        """Statistic and pval are alpha-independent; only H changes."""
        local_rng = np.random.default_rng(99)
        data = local_rng.standard_normal(500)

        stat_ref, pval_ref, _ = jarquebera(data, K=2, alpha=0.05)
        stat_test, pval_test, H_test = jarquebera(data, K=2, alpha=alpha)

        # stat and pval must be identical regardless of alpha
        npt.assert_allclose(
            stat_test, stat_ref, atol=0.0, rtol=0.0,
            err_msg=f"statistic changed with alpha={alpha}"
        )
        npt.assert_allclose(
            pval_test, pval_ref, atol=0.0, rtol=0.0,
            err_msg=f"pval changed with alpha={alpha}"
        )

        # H must satisfy H = (pval < alpha)
        # Ref: jarquebera.m:73
        assert H_test == (pval_test < alpha), (
            f"H mismatch: H={H_test}, pval={pval_test}, alpha={alpha}"
        )


class TestJarqueberaFormulaKnownValues:
    """Verify with hand-computed values (test_jarquebera_formula_known_values)."""

    def test_jarquebera_formula_known_values(self) -> None:
        """Cross-check against manually computed JB statistic."""
        # Use a small deterministic array where we can compute by hand
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
        T = len(data)
        K = 2

        # Step 1: Standardize with ddof=1
        # Ref: jarquebera.m:69-70
        z = data - np.mean(data)
        z = z / np.std(z, ddof=1)

        # Step 2: Compute JB terms
        # Ref: jarquebera.m:71
        skew_term = np.mean(z ** 3) ** 2 / 6.0
        kurt_term = (np.mean(z ** 4) - 3.0) ** 2 / 24.0
        expected_stat = (T - K) * (skew_term + kurt_term)

        # Step 3: Compute p-value
        # Ref: jarquebera.m:72
        expected_pval = 1.0 - chi2.cdf(expected_stat, 2)

        # Step 4: Decision
        # Ref: jarquebera.m:73
        expected_H = expected_pval < 0.05

        statistic, pval, H = jarquebera(data, K=K, alpha=0.05)

        # Use conftest assert_allclose wrapper for MFE-default tolerances
        assert_allclose(
            statistic, expected_stat,
            err_msg="JB statistic does not match hand-computed value",
        )
        assert_allclose(
            pval, expected_pval,
            err_msg="JB p-value does not match hand-computed value",
        )
        assert H == expected_H


class TestJarqueberaStdDdof1:
    """Verify MATLAB std (ddof=1) is used (test_jarquebera_std_ddof1)."""

    def test_jarquebera_std_ddof1(self) -> None:
        """Use small data where ddof=0 vs ddof=1 gives different results.

        Ref: jarquebera.m:70 — MATLAB ``std()`` uses N-1 divisor (ddof=1).
        """
        # With n=5, ddof=0 vs ddof=1 differ by sqrt(5/4) = 1.118
        data = np.array([1.0, 3.0, 5.0, 2.0, 9.0])
        T = len(data)
        K = 2

        # Compute with ddof=1 (MATLAB behavior)
        z1 = data - np.mean(data)
        z1 = z1 / np.std(z1, ddof=1)
        skew1 = np.mean(z1 ** 3) ** 2 / 6.0
        kurt1 = (np.mean(z1 ** 4) - 3.0) ** 2 / 24.0
        stat_ddof1 = (T - K) * (skew1 + kurt1)

        # Compute with ddof=0 (would be wrong)
        z0 = data - np.mean(data)
        z0 = z0 / np.std(z0, ddof=0)
        skew0 = np.mean(z0 ** 3) ** 2 / 6.0
        kurt0 = (np.mean(z0 ** 4) - 3.0) ** 2 / 24.0
        stat_ddof0 = (T - K) * (skew0 + kurt0)

        # Verify they differ
        assert not np.isclose(stat_ddof1, stat_ddof0), (
            "ddof=0 and ddof=1 gave same stat — test is not discriminating"
        )

        # Verify implementation matches ddof=1
        statistic, _, _ = jarquebera(data, K=K)
        npt.assert_allclose(
            statistic, stat_ddof1, atol=ATOL, rtol=RTOL,
            err_msg="Implementation does not match ddof=1 computation"
        )


# ---------------------------------------------------------------------------
# Phase 2: Input Validation Tests
# ---------------------------------------------------------------------------


class TestJarqueberaInputValidation:
    """Input validation error paths from jarquebera.m:53-65."""

    def test_jarquebera_empty_data_raises(self) -> None:
        """Empty array raises ValueError.

        Ref: jarquebera.m:53-55 — MATLAB: [T,C]=size(data); if ~any([T C]==1)
        """
        with pytest.raises(ValueError, match="[Dd]ata|[Ee]mpty|non-empty"):
            jarquebera(np.empty(0))

    def test_jarquebera_2d_data_handled(self) -> None:
        """2D column vector input is handled (flattened via ravel).

        Ref: jarquebera.m:54 — MATLAB accepts column vectors.
        Python implementation uses np.ravel() so 2D input should work.
        """
        data_1d = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        data_2d = data_1d.reshape(-1, 1)  # Column vector

        stat_1d, pval_1d, H_1d = jarquebera(data_1d)
        stat_2d, pval_2d, H_2d = jarquebera(data_2d)

        npt.assert_allclose(stat_1d, stat_2d, atol=0.0, rtol=0.0,
                            err_msg="2D column vector gives different stat")
        npt.assert_allclose(pval_1d, pval_2d, atol=0.0, rtol=0.0,
                            err_msg="2D column vector gives different pval")
        assert H_1d == H_2d

    def test_jarquebera_alpha_too_high_raises(self) -> None:
        """alpha > 1 raises ValueError.

        Ref: jarquebera.m:58-59 — MATLAB: if ~isscalar(alpha) || alpha>1 || alpha<0
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        with pytest.raises(ValueError, match="[Aa]lpha|scalar"):
            jarquebera(data, alpha=1.5)

    def test_jarquebera_alpha_negative_raises(self) -> None:
        """alpha < 0 raises ValueError.

        Ref: jarquebera.m:58-59
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        with pytest.raises(ValueError, match="[Aa]lpha|scalar"):
            jarquebera(data, alpha=-0.1)

    def test_jarquebera_negative_K_raises(self) -> None:
        """K < 0 raises ValueError.

        Ref: jarquebera.m:63-64 — MATLAB: if ~isscalar(K) || K<0 || K~=floor(K)
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        with pytest.raises(ValueError, match="[Kk]|integer|non-negative"):
            jarquebera(data, K=-1)

    def test_jarquebera_noninteger_K_raises(self) -> None:
        """Non-integer K raises ValueError.

        Ref: jarquebera.m:63-64 — MATLAB: K~=floor(K)
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        with pytest.raises((ValueError, TypeError)):
            jarquebera(data, K=2.5)


# ---------------------------------------------------------------------------
# Phase 3: Parity Tests (against MATLAB fixtures)
# ---------------------------------------------------------------------------


class TestJarqueberaParityNormal:
    """Compare against MATLAB fixture for normal data (test_jarquebera_parity_normal)."""

    @pytest.mark.parity
    def test_jarquebera_parity_normal(self, tests_fixture_dir: Path) -> None:
        """Verify numerical parity for normal data against MATLAB/Octave fixtures.

        Loads the ``jarquebera.npy`` fixture containing 54 test cases across
        6 datasets, 3 K values, and 3 alpha values. Tests the 3 normal
        datasets (normal_100, normal_500, normal_1000).
        """
        fixture = load_fixture_npy(tests_fixture_dir, "jarquebera")
        fixture_dict = fixture.item() if fixture.ndim == 0 else fixture

        K_values = fixture_dict["K_values"]  # [0, 2, 5]
        alpha_values = fixture_dict["alpha_values"]  # [0.01, 0.05, 0.10]

        # Test normal datasets (first 3 of 6)
        normal_datasets = ["normal_100", "normal_500", "normal_1000"]
        for ds_idx, ds_name in enumerate(normal_datasets):
            input_data = fixture_dict[ds_name].ravel()

            for k_idx, K in enumerate(K_values):
                for a_idx, alpha in enumerate(alpha_values):
                    # Fixture ordering: dataset * (num_K * num_alpha)
                    #                   + K_idx * num_alpha + alpha_idx
                    case_idx = ds_idx * len(K_values) * len(alpha_values) \
                        + k_idx * len(alpha_values) + a_idx

                    expected_stat = float(fixture_dict["statistic"][case_idx, 0])
                    expected_pval = float(fixture_dict["pval"][case_idx, 0])
                    expected_H = bool(fixture_dict["H"][case_idx, 0])

                    stat, pval, H = jarquebera(input_data, K=int(K), alpha=float(alpha))

                    npt.assert_allclose(
                        stat, expected_stat, atol=ATOL, rtol=RTOL,
                        err_msg=(
                            f"stat mismatch for {ds_name}, K={K}, alpha={alpha} "
                            f"(case {case_idx})"
                        ),
                    )
                    npt.assert_allclose(
                        pval, expected_pval, atol=ATOL, rtol=RTOL,
                        err_msg=(
                            f"pval mismatch for {ds_name}, K={K}, alpha={alpha} "
                            f"(case {case_idx})"
                        ),
                    )
                    assert H == expected_H, (
                        f"H mismatch for {ds_name}, K={K}, alpha={alpha}: "
                        f"got {H}, expected {expected_H}"
                    )


class TestJarqueberaParityNonnormal:
    """Compare against MATLAB fixture for non-normal data (test_jarquebera_parity_nonnormal)."""

    @pytest.mark.parity
    def test_jarquebera_parity_nonnormal(self, tests_fixture_dir: Path) -> None:
        """Verify numerical parity for chi-squared data against MATLAB/Octave fixtures.

        The chi-squared datasets are highly non-normal (skewness=2, excess
        kurtosis=6 for df=2) and should all reject normality.
        """
        fixture = load_fixture_npy(tests_fixture_dir, "jarquebera")
        fixture_dict = fixture.item() if fixture.ndim == 0 else fixture

        K_values = fixture_dict["K_values"]
        alpha_values = fixture_dict["alpha_values"]
        num_K = len(K_values)
        num_alpha = len(alpha_values)

        # Test chi2 datasets (indices 3, 4, 5 of 6)
        chi2_datasets = ["chi2_100", "chi2_500", "chi2_1000"]
        for ds_offset, ds_name in enumerate(chi2_datasets):
            ds_idx = 3 + ds_offset  # chi2 datasets start at index 3
            input_data = fixture_dict[ds_name].ravel()

            for k_idx, K in enumerate(K_values):
                for a_idx, alpha in enumerate(alpha_values):
                    case_idx = ds_idx * num_K * num_alpha \
                        + k_idx * num_alpha + a_idx

                    expected_stat = float(fixture_dict["statistic"][case_idx, 0])
                    expected_pval = float(fixture_dict["pval"][case_idx, 0])
                    expected_H = bool(fixture_dict["H"][case_idx, 0])

                    stat, pval, H = jarquebera(input_data, K=int(K), alpha=float(alpha))

                    npt.assert_allclose(
                        stat, expected_stat, atol=ATOL, rtol=RTOL,
                        err_msg=(
                            f"stat mismatch for {ds_name}, K={K}, alpha={alpha} "
                            f"(case {case_idx})"
                        ),
                    )
                    npt.assert_allclose(
                        pval, expected_pval, atol=ATOL, rtol=RTOL,
                        err_msg=(
                            f"pval mismatch for {ds_name}, K={K}, alpha={alpha} "
                            f"(case {case_idx})"
                        ),
                    )
                    assert H == expected_H, (
                        f"H mismatch for {ds_name}, K={K}, alpha={alpha}: "
                        f"got {H}, expected {expected_H}"
                    )


class TestJarqueberaParityMultipleK:
    """Compare across K values against MATLAB fixtures (test_jarquebera_parity_multiple_K)."""

    @pytest.mark.parity
    @pytest.mark.parametrize("K_idx,K", [(0, 0), (1, 2), (2, 5)])
    def test_jarquebera_parity_multiple_K(
        self, tests_fixture_dir: Path, K_idx: int, K: int
    ) -> None:
        """Verify K=0, K=2, K=5 each match MATLAB for all 6 datasets.

        Ref: jarquebera.m:71 — statistic = (T-K)*(...) where K varies.
        """
        fixture = load_fixture_npy(tests_fixture_dir, "jarquebera")
        fixture_dict = fixture.item() if fixture.ndim == 0 else fixture

        alpha_values = fixture_dict["alpha_values"]
        num_K = len(fixture_dict["K_values"])
        num_alpha = len(alpha_values)
        dataset_names = fixture_dict["dataset_names"]

        # Use default alpha=0.05 → alpha index 1
        a_idx = 1  # alpha=0.05

        for ds_idx, ds_name in enumerate(dataset_names):
            input_data = fixture_dict[str(ds_name)].ravel()
            case_idx = ds_idx * num_K * num_alpha + K_idx * num_alpha + a_idx

            expected_stat = float(fixture_dict["statistic"][case_idx, 0])
            expected_pval = float(fixture_dict["pval"][case_idx, 0])

            stat, pval, _ = jarquebera(input_data, K=K, alpha=0.05)

            npt.assert_allclose(
                stat, expected_stat, atol=ATOL, rtol=RTOL,
                err_msg=f"stat mismatch for {ds_name} with K={K}",
            )
            npt.assert_allclose(
                pval, expected_pval, atol=ATOL, rtol=RTOL,
                err_msg=f"pval mismatch for {ds_name} with K={K}",
            )


class TestJarqueberaParityIndividualFixtures:
    """Parity against individual fixture files (jarquebera_jb_*.npy)."""

    @pytest.mark.parity
    def test_jarquebera_parity_individual_fixture(
        self, tests_fixture_dir: Path
    ) -> None:
        """Compare against individually saved fixture files.

        These individual fixtures (jarquebera_jb_data, _stat, _pval, _H)
        contain a single test case for quick smoke-test verification.
        """
        jb_data = load_fixture_npy(tests_fixture_dir, "jarquebera_jb_data")
        jb_stat = load_fixture_npy(tests_fixture_dir, "jarquebera_jb_stat")
        jb_pval = load_fixture_npy(tests_fixture_dir, "jarquebera_jb_pval")
        jb_H = load_fixture_npy(tests_fixture_dir, "jarquebera_jb_H")

        input_data = jb_data.ravel()
        expected_stat = float(jb_stat)
        expected_pval = float(jb_pval)
        expected_H = bool(jb_H)

        stat, pval, H = jarquebera(input_data)

        # Use conftest assert_allclose wrapper with MFE-default tolerances
        assert_allclose(
            stat, expected_stat,
            err_msg="stat mismatch against individual fixture",
        )
        assert_allclose(
            pval, expected_pval,
            err_msg="pval mismatch against individual fixture",
        )
        assert H == expected_H, (
            f"H mismatch: got {H}, expected {expected_H}"
        )


# ---------------------------------------------------------------------------
# Phase 4: Return Type and Shape Tests
# ---------------------------------------------------------------------------


class TestJarqueberaReturnTypes:
    """Return type and invariant tests."""

    def test_jarquebera_return_types(self, rng: np.random.Generator) -> None:
        """Statistic is float, pval is float, H is bool.

        Ref: jarquebera.py signature → tuple[float, float, bool]
        """
        data = rng.standard_normal(100)
        statistic, pval, H = jarquebera(data)

        assert isinstance(statistic, (float, np.floating)), (
            f"statistic type is {type(statistic)}, expected float"
        )
        assert isinstance(pval, (float, np.floating)), (
            f"pval type is {type(pval)}, expected float"
        )
        assert isinstance(H, bool), (
            f"H type is {type(H)}, expected bool"
        )

    def test_jarquebera_stat_nonnegative(self, rng: np.random.Generator) -> None:
        """JB statistic must be non-negative (squared terms only).

        Ref: jarquebera.m:71 — (T-K) * (skew^2/6 + kurt^2/24)
        All terms are squared → statistic ≥ 0 always.
        """
        # Test with various data patterns
        for seed in [0, 42, 99, 777]:
            local_rng = np.random.default_rng(seed)
            data = local_rng.standard_normal(200)
            statistic, _, _ = jarquebera(data)
            assert statistic >= 0.0, (
                f"Negative JB statistic ({statistic}) with seed={seed}"
            )

    def test_jarquebera_pval_range(self, rng: np.random.Generator) -> None:
        """P-value must be in [0, 1].

        Ref: jarquebera.m:72 — pval = 1 - chi2cdf(statistic, 2)
        Since chi2.cdf returns values in [0, 1], pval ∈ [0, 1].
        """
        for seed in [0, 42, 99, 777]:
            local_rng = np.random.default_rng(seed)
            data = local_rng.standard_normal(200)
            _, pval, _ = jarquebera(data)
            assert 0.0 <= pval <= 1.0, (
                f"P-value ({pval}) outside [0, 1] with seed={seed}"
            )

    def test_jarquebera_chi2_2df(self, rng: np.random.Generator) -> None:
        """Verify chi-squared with 2 degrees of freedom is used for p-value.

        Ref: jarquebera.m:72 — ``pval = 1 - chi2cdf(statistic, 2)``
        Independently compute p-value using scipy.stats.chi2 to confirm.
        """
        data = rng.standard_normal(300)
        statistic, pval, _ = jarquebera(data)

        # Independent p-value calculation using chi2.sf (survival function)
        # chi2.sf(x, df) = 1 - chi2.cdf(x, df)
        expected_pval = float(chi2.sf(statistic, 2))

        npt.assert_allclose(
            pval, expected_pval, atol=ATOL, rtol=RTOL,
            err_msg="p-value does not match chi2(df=2) survival function",
        )

        # Also verify via the CDF formulation explicitly
        expected_pval_cdf = float(1.0 - chi2.cdf(statistic, 2))
        npt.assert_allclose(
            pval, expected_pval_cdf, atol=ATOL, rtol=RTOL,
            err_msg="p-value does not match 1 - chi2.cdf(stat, 2)",
        )


# ---------------------------------------------------------------------------
# Additional Edge Case Tests
# ---------------------------------------------------------------------------


class TestJarqueberaEdgeCases:
    """Additional edge cases for robustness."""

    def test_jarquebera_constant_data(self) -> None:
        """Constant data (zero variance) should return stat=0, pval=1, H=False.

        When all observations are identical, std=0, skewness and kurtosis
        are undefined. The implementation should handle this gracefully.
        """
        data = np.full(100, 5.0)
        statistic, pval, H = jarquebera(data)

        assert statistic == 0.0, (
            f"Constant data should have stat=0, got {statistic}"
        )
        assert pval == 1.0, (
            f"Constant data should have pval=1, got {pval}"
        )
        assert H is False

    def test_jarquebera_boundary_alpha_zero(self) -> None:
        """alpha=0 boundary: H should always be False (never reject).

        Ref: jarquebera.m:73 — H = pval < alpha; with alpha=0, no pval < 0.
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        statistic, pval, H = jarquebera(data, alpha=0.0)
        assert H is False, "H should be False when alpha=0"

    def test_jarquebera_boundary_alpha_one(self) -> None:
        """alpha=1 boundary: H should be True when pval < 1.

        Ref: jarquebera.m:73 — H = pval < alpha; with alpha=1, pval < 1 → H=True
        unless pval=1 exactly.
        """
        local_rng = np.random.default_rng(42)
        data = local_rng.standard_normal(100)
        statistic, pval, H = jarquebera(data, alpha=1.0)

        # For non-constant data, pval is typically < 1 → H = True
        if pval < 1.0:
            assert H is True

    def test_jarquebera_small_sample(self) -> None:
        """Minimum sample size (3 observations for ddof=1 std to be defined)."""
        data = np.array([1.0, 2.0, 3.0])
        statistic, pval, H = jarquebera(data, K=0)

        assert isinstance(statistic, float)
        assert statistic >= 0.0
        assert 0.0 <= pval <= 1.0

    def test_jarquebera_K_equals_T_minus_one(self) -> None:
        """K = T-1 gives stat ≈ factor * 1, still valid.

        Ref: jarquebera.m:71 — stat = (T-K)*(...); with K=T-1, factor = 1.
        """
        data = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
        T = len(data)
        statistic, pval, H = jarquebera(data, K=T - 1)
        assert statistic >= 0.0

    def test_jarquebera_returns_tuple_of_three(
        self, rng: np.random.Generator
    ) -> None:
        """Return value must be a tuple of exactly 3 elements."""
        data = rng.standard_normal(100)
        result = jarquebera(data)
        assert isinstance(result, tuple), (
            f"Expected tuple, got {type(result)}"
        )
        assert len(result) == 3, (
            f"Expected 3 elements, got {len(result)}"
        )


# ---------------------------------------------------------------------------
# Comprehensive Parity Sweep
# ---------------------------------------------------------------------------


class TestJarqueberaFullParitySweep:
    """Full parity sweep across all 54 test cases in the main fixture."""

    @pytest.mark.parity
    def test_jarquebera_full_parity_sweep(self, tests_fixture_dir: Path) -> None:
        """Iterate through ALL 54 fixture test cases and verify parity.

        This is the definitive parity test covering all combinations of
        6 datasets × 3 K values × 3 alpha values.
        """
        fixture = load_fixture_npy(tests_fixture_dir, "jarquebera")
        fixture_dict = fixture.item() if fixture.ndim == 0 else fixture

        K_values = fixture_dict["K_values"]
        alpha_values = fixture_dict["alpha_values"]
        dataset_names = fixture_dict["dataset_names"]
        num_K = len(K_values)
        num_alpha = len(alpha_values)
        total_cases = int(fixture_dict["num_test_cases"])

        assert total_cases == 54, f"Expected 54 test cases, got {total_cases}"

        failures: list[str] = []
        case_idx = 0

        for ds_idx, ds_name in enumerate(dataset_names):
            input_data = fixture_dict[str(ds_name)].ravel()

            for k_idx, K in enumerate(K_values):
                for a_idx, alpha in enumerate(alpha_values):
                    expected_stat = float(
                        fixture_dict["statistic"][case_idx, 0]
                    )
                    expected_pval = float(fixture_dict["pval"][case_idx, 0])
                    expected_H = bool(fixture_dict["H"][case_idx, 0])

                    stat, pval, H = jarquebera(
                        input_data, K=int(K), alpha=float(alpha)
                    )

                    try:
                        npt.assert_allclose(
                            stat, expected_stat, atol=ATOL, rtol=RTOL,
                        )
                    except AssertionError:
                        failures.append(
                            f"Case {case_idx} ({ds_name}, K={K}, "
                            f"alpha={alpha}): stat {stat} != {expected_stat}"
                        )

                    try:
                        npt.assert_allclose(
                            pval, expected_pval, atol=ATOL, rtol=RTOL,
                        )
                    except AssertionError:
                        failures.append(
                            f"Case {case_idx} ({ds_name}, K={K}, "
                            f"alpha={alpha}): pval {pval} != {expected_pval}"
                        )

                    if H != expected_H:
                        failures.append(
                            f"Case {case_idx} ({ds_name}, K={K}, "
                            f"alpha={alpha}): H {H} != {expected_H}"
                        )

                    case_idx += 1

        assert case_idx == total_cases, (
            f"Processed {case_idx} cases, expected {total_cases}"
        )
        assert len(failures) == 0, (
            f"{len(failures)} parity failures:\n" + "\n".join(failures)
        )
