"""
Smoke test / demo module for all realized volatility estimators.

Translated from ``realized/realized_test.m`` in the MFE Toolbox (Version 4.0).
Exercises every realized estimator with both real (ES_20090817) and synthetic
(geometric Brownian motion) data to verify that all functions execute without
error under representative parameter combinations.

This module serves as a comprehensive integration / smoke test — it does NOT
assert numerical parity (those checks belong in the pytest suite under
``tests/test_realized/``).  Instead it confirms that every public estimator
can be called with typical arguments, handles all five sampling types, and
returns results without raising exceptions.

Migrated from: ``realized/realized_test.m`` (MFE Toolbox Version 4.0)
Original author: Kevin Sheppard (kevin.sheppard@economics.ox.ac.uk)

Usage
-----
Run as a module::

    python -m mfe_toolbox.realized.realized_test

Or call the function directly::

    from mfe_toolbox.realized.realized_test import realized_test
    realized_test()

See Also
--------
mfe_toolbox.realized.realized_variance : Core RV estimator.
mfe_toolbox.realized.realized_kernel : Realized kernel estimator.
mfe_toolbox.realized.realized_range : Range-based estimator.
mfe_toolbox.realized.realized_quantile_variance : Quantile RV.
"""

from __future__ import annotations

import os
import warnings

import numpy as np

# ---------------------------------------------------------------------------
# Internal imports — all from depends_on_files
# ---------------------------------------------------------------------------
from mfe_toolbox.realized.realized_variance import realized_variance
from mfe_toolbox.realized.realized_semivariance import realized_semivariance
from mfe_toolbox.realized.realized_bipower_variation import realized_bipower_variation
from mfe_toolbox.realized.realized_quarticity import realized_quarticity
from mfe_toolbox.realized.realized_covariance import realized_covariance
from mfe_toolbox.realized.realized_kernel import realized_kernel  # noqa: F401 — imported for completeness
from mfe_toolbox.realized.realized_range import realized_range
from mfe_toolbox.realized.realized_quantile_variance import realized_quantile_variance
from mfe_toolbox.realized.realized_twoscale_variance import realized_twoscale_variance
from mfe_toolbox.realized.realized_variance_optimal_sampling import (
    realized_variance_optimal_sampling,
)
from mfe_toolbox.realized.seconds2wall import seconds2wall
from mfe_toolbox.realized.wall2seconds import wall2seconds


# ---------------------------------------------------------------------------
# Data loading helper
# ---------------------------------------------------------------------------


def _resolve_fixture_dir() -> str:
    """Resolve the directory containing ES_20090817 fixture data.

    Checks the optional ``MFE_FIXTURE_DIR`` environment variable first
    (per AAP §0.7.2), then falls back to the default test fixtures
    location relative to the repository root.

    Returns
    -------
    str
        Absolute path to the fixture directory.
    """
    # Ref: AAP §0.7.2 — optional MFE_FIXTURE_DIR override for CI
    env_dir = os.environ.get("MFE_FIXTURE_DIR")
    if env_dir is not None:
        candidate = os.path.join(env_dir, "realized")
        if os.path.exists(candidate):
            return candidate
        # Also check if env_dir already points to the realized subdir
        if os.path.exists(env_dir):
            return env_dir

    # Default: tests/fixtures/realized relative to project root
    # Walk up from this module's location to the repo root
    module_dir = os.path.dirname(os.path.abspath(__file__))  # mfe_toolbox/realized/
    package_root = os.path.dirname(module_dir)                # mfe_toolbox/
    repo_root = os.path.dirname(package_root)                 # project root
    return os.path.join(repo_root, "tests", "fixtures", "realized")


def _load_es_data() -> tuple[np.ndarray, np.ndarray]:
    """Load ES_20090817 trade price and time arrays from fixture files.

    Attempts multiple loading strategies:
    1. Separate .npy files for price and time (preferred)
    2. Combined .npy file (legacy)
    3. scipy.io.loadmat fallback for .mat format

    Returns
    -------
    price : np.ndarray
        1-D array of trade prices.
    time : np.ndarray
        1-D array of trade times in wall-clock (HHMMSS) format.

    Raises
    ------
    FileNotFoundError
        If no suitable data file is found.
    """
    fixture_dir = _resolve_fixture_dir()

    # Strategy 1: Separate .npy files (generated by convert_fixtures.py)
    price_path = os.path.join(fixture_dir, "ES_20090817_trades_price.npy")
    time_path = os.path.join(fixture_dir, "ES_20090817_trades_time.npy")
    if os.path.exists(price_path) and os.path.exists(time_path):
        price = np.load(price_path).ravel().astype(np.float64)
        time_arr = np.load(time_path).ravel().astype(np.float64)
        return price, time_arr

    # Strategy 2: Combined .npy file (allow_pickle for structured arrays)
    combined_path = os.path.join(fixture_dir, "ES_20090817.npy")
    if os.path.exists(combined_path):
        try:
            data = np.load(combined_path, allow_pickle=True)
            # May be a structured array or dict-like object
            if hasattr(data, 'item'):
                data = data.item()
            if isinstance(data, dict):
                # Extract trades.price and trades.time
                trades = data.get("trades", data)
                if isinstance(trades, dict):
                    price = np.asarray(trades["price"], dtype=np.float64).ravel()
                    time_arr = np.asarray(trades["time"], dtype=np.float64).ravel()
                    return price, time_arr
        except Exception:
            pass  # Fall through to scipy fallback

    # Strategy 3: scipy.io.loadmat fallback
    # Ref: realized_test.m:1 — load ES_20090817
    mat_path = os.path.join(fixture_dir, "ES_20090817.mat")
    if os.path.exists(mat_path):
        try:
            from scipy.io import loadmat
            mat_data = loadmat(mat_path)
            # MATLAB struct: trades.price, trades.time
            if "trades" in mat_data:
                trades = mat_data["trades"]
                price = np.asarray(
                    trades["price"][0, 0], dtype=np.float64
                ).ravel()
                time_arr = np.asarray(
                    trades["time"][0, 0], dtype=np.float64
                ).ravel()
                return price, time_arr
            # Flat variables in .mat
            if "price" in mat_data and "time" in mat_data:
                price = np.asarray(mat_data["price"], dtype=np.float64).ravel()
                time_arr = np.asarray(mat_data["time"], dtype=np.float64).ravel()
                return price, time_arr
        except ImportError:
            pass  # scipy not available

    raise FileNotFoundError(
        f"Could not locate ES_20090817 data in '{fixture_dir}'. "
        "Ensure fixture files have been generated via "
        "'python scripts/convert_fixtures.py'."
    )


# ---------------------------------------------------------------------------
# Main smoke test function
# ---------------------------------------------------------------------------


def realized_test() -> None:
    """Run smoke test exercising all realized estimators.

    Loads ES_20090817 high-frequency trade data, then calls every realized
    estimator with various parameter combinations to verify they execute
    without error.  Also generates synthetic Brownian motion data for
    additional testing of the quantile variance estimator.

    The test sequence faithfully mirrors the original MATLAB
    ``realized_test.m`` script, with Python-specific adaptations for
    function signatures, 0-based indexing, and snake_case conventions.

    Raises
    ------
    FileNotFoundError
        If the ES_20090817 fixture data cannot be located.
    """
    # ==================================================================
    # Phase 1: Load data
    # Ref: realized_test.m:1-3 — load ES_20090817; price=trades.price; time=trades.time
    # ==================================================================
    print("Loading ES_20090817 data...")
    price, time = _load_es_data()
    print(f"  Loaded {len(price)} trade observations.")

    # ==================================================================
    # Phase 2: Set up time parameters
    # Ref: realized_test.m:4-8
    # ==================================================================
    # Ref: realized_test.m:4 — timeType='wall'
    time_type: str = 'wall'

    # Ref: realized_test.m:5 — fixedInterval = seconds2wall(wall2seconds(83000):300:wall2seconds(150000))
    # MATLAB colon operator start:step:end is inclusive; Python np.arange end is exclusive
    # so we add 1 to the stop value to make it inclusive.
    ws_start = wall2seconds(np.array([83000.0]))[0]   # 29800.0 (8:30 AM)
    ws_stop = wall2seconds(np.array([150000.0]))[0]    # 54000.0 (3:00 PM)
    fixed_interval = seconds2wall(
        np.arange(ws_start, ws_stop + 1, 300.0)
    )

    # Ref: realized_test.m:6 — samplingInterval=fixedInterval
    sampling_interval = fixed_interval

    # Ref: realized_test.m:7 — samplingType='fixed'
    sampling_type: str = 'Fixed'

    # Ref: realized_test.m:8 — subsamples = 5
    subsamples: int = 5

    # ==================================================================
    # Phase 3: Test realized_variance_optimal_sampling
    # Ref: realized_test.m:11
    # ==================================================================
    print("\n--- Testing realized_variance_optimal_sampling ---")
    try:
        rv, rv_debiased, rv_ss, rv_debiased_ss, diag = (
            realized_variance_optimal_sampling(
                price, time, time_type, 'businesstime', 1, subsamples=10
            )
        )
        print(f"  RV={rv:.8f}, RV_debiased={rv_debiased:.8f}")
        print(f"  RV_SS={rv_ss:.8f}, RV_debiased_SS={rv_debiased_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_variance_optimal_sampling: {exc}")

    # Ref: realized_test.m:13 — p=price (used later, now overwritten by synthetic data)

    # ==================================================================
    # Phase 4: Generate synthetic data and test quantile/range estimators
    # Ref: realized_test.m:15-18
    # ==================================================================
    print("\n--- Generating synthetic Brownian motion data ---")
    # Ref: realized_test.m:15 — r = randn(390*300,1)/sqrt(390*300)
    # AAP §0.7.3: randn → numpy.random.default_rng().standard_normal()
    rng = np.random.default_rng(42)
    r = rng.standard_normal(390 * 300) / np.sqrt(390 * 300)

    # Ref: realized_test.m:16-17 — p=cumsum([0;r]); p=exp(p);
    # MATLAB cumsum([0;r]) prepends 0 to the column vector before cumsum
    p_synth = np.exp(np.cumsum(np.concatenate(([0.0], r))))
    t_synth = np.linspace(0.0, 1.0, len(p_synth))

    print(f"  Synthetic price path: {len(p_synth)} observations")

    # Ref: realized_test.m:18
    # realized_quantile_variance(p,linspace(0,1,length(p)),'unit','businessTime',300,1/2,2,true,true)
    print("  Testing realized_quantile_variance on synthetic data...")
    try:
        rq, rq_ss, rq_diag = realized_quantile_variance(
            p_synth,
            t_synth,
            'unit',
            'businessTime',
            300,
            0.5,        # quantiles = 1/2
            2,           # block_size = 2
            True,        # symmetric = True
            True,        # overlap = True
        )
        print(f"  QRV={float(rq):.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_quantile_variance (synthetic): {exc}")

    # Ref: realized_test.m:20 — realized_quantile_variance_v2 call
    # NOTE: realized_quantile_variance_v2 does NOT exist in the AAP file map;
    # this call is intentionally omitted per migration instructions.

    # Ref: realized_test.m:23 — second call to realized_variance_optimal_sampling
    # The MATLAB source passes an undefined 'options' variable; use None.
    print("  Testing realized_variance_optimal_sampling (with subsamples)...")
    try:
        rv2, rv2d, rv2ss, rv2dss, diag2 = realized_variance_optimal_sampling(
            price, time, time_type, 'businesstime', 1,
            subsamples=subsamples, options=None
        )
        print(f"  RV={rv2:.8f}, RV_debiased={rv2d:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_variance_optimal_sampling (2nd): {exc}")

    # ==================================================================
    # Phase 5: Range and twoscale variance tests
    # Ref: realized_test.m:26-30
    # ==================================================================
    print("\n--- Testing realized_range ---")
    # Ref: realized_test.m:26 — realized_range(price,time,timeType,samplingType,samplingInterval,7)
    try:
        rr, rr_ss, rr_diag = realized_range(
            price, time, time_type, sampling_type, sampling_interval,
            samples_per_bin=7
        )
        print(f"  RR={rr:.8f}, RR_SS={rr_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_range: {exc}")

    print("\n--- Testing realized_twoscale_variance ---")
    # Ref: realized_test.m:29 — realized_twoscale_variance(price,time,timeType,'businessTime',15,15)
    try:
        rvts, rvts_ss, rvts_diag = realized_twoscale_variance(
            price, time, time_type, 'businessTime', 15, subsamples=15
        )
        print(f"  TSRV={rvts:.8f}, TSRV_SS={rvts_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_twoscale_variance (15,15): {exc}")

    # Ref: realized_test.m:30 — realized_twoscale_variance(price,time,timeType,'businessTime',15)
    try:
        rvts2, rvts2_ss, rvts2_diag = realized_twoscale_variance(
            price, time, time_type, 'businessTime', 15
        )
        print(f"  TSRV={rvts2:.8f}, TSRV_SS={rvts2_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_twoscale_variance (15): {exc}")

    # ==================================================================
    # Phase 6: Main loop over 5 sampling types
    # Ref: realized_test.m:33-87
    # ==================================================================
    print("\n--- Main sampling type loop ---")

    # Ref: realized_test.m:33 — sTypes = {'CalendarTime','CalendarUniform',
    #   'BusinessTime','BusinessUniform','Fixed'}
    s_types: list[str] = [
        'CalendarTime', 'CalendarUniform', 'BusinessTime',
        'BusinessUniform', 'Fixed',
    ]

    # Ref: realized_test.m:34 — sTypeVals = {{60,300},{78,390},{1,50,300},{68,390},{samplingInterval}}
    # MATLAB cell arrays → Python list of lists
    # NOTE: For 'Fixed' type, the value is the precomputed fixed_interval array.
    s_type_vals: list[list] = [
        [60, 300],                 # CalendarTime intervals
        [78, 390],                 # CalendarUniform intervals
        [1, 50, 300],              # BusinessTime intervals
        [68, 390],                 # BusinessUniform intervals
        [sampling_interval],       # Fixed — uses the precomputed array
    ]

    # Ref: realized_test.m:36-42 — realized_quantile_variance_v2 calls
    # NOTE: realized_quantile_variance_v2 does NOT exist in the AAP file map;
    # all v2 calls are intentionally omitted per migration instructions.

    # Ref: realized_test.m:45-87 — main nested loop
    for i, samp_type in enumerate(s_types):
        vals = s_type_vals[i]
        for j, samp_interval in enumerate(vals):
            print(f"\n  [{samp_type}] interval={samp_interval if np.isscalar(samp_interval) else 'Fixed array'}")

            # Suppress warnings during smoke test to keep output clean
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")

                # ----------------------------------------------------------
                # Realized Variance
                # Ref: realized_test.m:50-51
                # ----------------------------------------------------------
                try:
                    # Ref: realized_test.m:50 — realized_variance without subsamples
                    rv_result = realized_variance(
                        price, time, time_type, samp_type, samp_interval
                    )
                    print(f"    RV = {rv_result[0]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_variance: {exc}")

                try:
                    # Ref: realized_test.m:51 — realized_variance with subsamples
                    rv_ss_result = realized_variance(
                        price, time, time_type, samp_type, samp_interval,
                        subsamples=subsamples
                    )
                    print(f"    RV_SS = {rv_ss_result[1]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_variance (SS): {exc}")

                # ----------------------------------------------------------
                # Realized Semivariance
                # Ref: realized_test.m:52-53
                # ----------------------------------------------------------
                try:
                    # Ref: realized_test.m:52 — realized_semivariance without subsamples
                    rsv_result = realized_semivariance(
                        price, time, time_type, samp_type, samp_interval
                    )
                    print(f"    RSV_neg = {rsv_result[0]:.8f}, RSV_pos = {rsv_result[1]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_semivariance: {exc}")

                try:
                    # Ref: realized_test.m:53 — realized_semivariance with subsamples
                    rsv_ss_result = realized_semivariance(
                        price, time, time_type, samp_type, samp_interval,
                        subsamples=subsamples
                    )
                    print(f"    RSV_neg_SS = {rsv_ss_result[2]:.8f}, RSV_pos_SS = {rsv_ss_result[3]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_semivariance (SS): {exc}")

                # ----------------------------------------------------------
                # Realized Bipower Variation
                # Ref: realized_test.m:54-59
                # ----------------------------------------------------------
                try:
                    # Ref: realized_test.m:54 — bipower variation (no skip, no subsamples)
                    bv_result = realized_bipower_variation(
                        price, time, time_type, samp_type, samp_interval
                    )
                    print(f"    BPV = {bv_result[0]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_bipower_variation: {exc}")

                try:
                    # Ref: realized_test.m:55 — bipower variation (no skip, with subsamples)
                    # MATLAB: realized_bipower_variation(...,[],subsamples)
                    # Python: skip defaults to 0, just pass subsamples
                    bv_ss_result = realized_bipower_variation(
                        price, time, time_type, samp_type, samp_interval,
                        subsamples=subsamples
                    )
                    print(f"    BPV_SS = {bv_ss_result[1]:.8f}")
                except Exception as exc:
                    print(f"    [WARN] realized_bipower_variation (SS): {exc}")

                # Ref: realized_test.m:56-59 — loop skip = 0:1
                for skip_val in [0, 1]:
                    try:
                        # Ref: realized_test.m:57
                        bv_skip = realized_bipower_variation(
                            price, time, time_type, samp_type, samp_interval,
                            skip=skip_val
                        )
                        print(f"    BPV(skip={skip_val}) = {bv_skip[0]:.8f}")
                    except Exception as exc:
                        print(f"    [WARN] realized_bipower_variation (skip={skip_val}): {exc}")

                    try:
                        # Ref: realized_test.m:58
                        bv_skip_ss = realized_bipower_variation(
                            price, time, time_type, samp_type, samp_interval,
                            skip=skip_val, subsamples=subsamples
                        )
                        print(f"    BPV_SS(skip={skip_val}) = {bv_skip_ss[1]:.8f}")
                    except Exception as exc:
                        print(f"    [WARN] realized_bipower_variation (skip={skip_val}, SS): {exc}")

                # ----------------------------------------------------------
                # Realized Quarticity
                # Ref: realized_test.m:63-76
                # ----------------------------------------------------------
                # Ref: realized_test.m:63 — default (BNS, skip=0, subsamples=1)
                try:
                    qt_result = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval
                    )
                    print(f"    QT(BNS) = {qt_result[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (default): {exc}")

                # Ref: realized_test.m:64 — QType='Quadpower'
                try:
                    qt_qp = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        quarticity_type='Quadpower'
                    )
                    print(f"    QT(Quadpower) = {qt_qp[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (Quadpower): {exc}")

                # Ref: realized_test.m:65 — skip=1 (QType=default BNS)
                try:
                    qt_s1 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        skip=1
                    )
                    print(f"    QT(skip=1) = {qt_s1[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (skip=1): {exc}")

                # Ref: realized_test.m:66 — subsamples=2 (QType=default, skip=default)
                try:
                    qt_ss2 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        subsamples=2
                    )
                    print(f"    QT(subsamples=2) = {qt_ss2[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (subsamples=2): {exc}")

                # Ref: realized_test.m:67 — all defaults (same as line 63)
                try:
                    realized_quarticity(
                        price, time, time_type, samp_type, samp_interval
                    )
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (all defaults): {exc}")

                # Ref: realized_test.m:68 — skip=1, subsamples=2
                try:
                    qt_s1ss2 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        skip=1, subsamples=2
                    )
                    print(f"    QT(skip=1, SS=2) = {qt_s1ss2[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (skip=1, SS=2): {exc}")

                # Ref: realized_test.m:69 — QType='Quadpower', skip=1
                try:
                    qt_qps1 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        skip=1, quarticity_type='Quadpower'
                    )
                    print(f"    QT(Quadpower, skip=1) = {qt_qps1[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (Quadpower, skip=1): {exc}")

                # Ref: realized_test.m:70 — QType='Quadpower', skip=1, subsamples=2
                try:
                    qt_qps1ss2 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        skip=1, quarticity_type='Quadpower', subsamples=2
                    )
                    print(f"    QT(Quadpower, skip=1, SS=2) = {qt_qps1ss2[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (Quadpower, skip=1, SS=2): {exc}")

                # Ref: realized_test.m:71 — QType='Quadpower', skip=default, subsamples=2
                try:
                    qt_qpss2 = realized_quarticity(
                        price, time, time_type, samp_type, samp_interval,
                        quarticity_type='Quadpower', subsamples=2
                    )
                    print(f"    QT(Quadpower, SS=2) = {qt_qpss2[0]:.8e}")
                except Exception as exc:
                    print(f"    [WARN] realized_quarticity (Quadpower, SS=2): {exc}")

                # Ref: realized_test.m:72-76 — nested loop over skip and QType
                for skip_val in [0, 1]:
                    # Ref: realized_test.m:73 — for QType = {[],'BNS','Tripower','Quadpower'}
                    # MATLAB [] means use default; in Python default is 'BNS'
                    for q_type in ['BNS', 'BNS', 'Tripower', 'Quadpower']:
                        # Note: first 'BNS' corresponds to MATLAB [] (default),
                        # second 'BNS' is the explicit string.
                        # Ref: realized_test.m:74
                        try:
                            realized_quarticity(
                                price, time, time_type, samp_type, samp_interval,
                                skip=skip_val, quarticity_type=q_type,
                                subsamples=subsamples
                            )
                        except Exception as exc:
                            print(f"    [WARN] realized_quarticity "
                                  f"(skip={skip_val}, QT={q_type}): {exc}")

                # ----------------------------------------------------------
                # Realized Covariance
                # Ref: realized_test.m:78-83
                # Only called when sampling type does NOT contain 'Bus'
                # Ref: realized_test.m:78 — if ~strfind(samplingType,'Bus')
                # Python: 'Bus' in samp_type → skip if True
                # ----------------------------------------------------------
                if 'Bus' not in samp_type:
                    # Ref: realized_test.m:79 — single series, no subsamples
                    try:
                        rc_result = realized_covariance(
                            [price], [time], time_type, samp_type, samp_interval
                        )
                        print(f"    RC (1-series) = {float(rc_result[0]):.8f}")
                    except Exception as exc:
                        print(f"    [WARN] realized_covariance (1-series): {exc}")

                    # Ref: realized_test.m:80 — single series, subsamples=5
                    try:
                        rc_ss_result = realized_covariance(
                            [price], [time], time_type, samp_type, samp_interval,
                            subsamples=5
                        )
                        print(f"    RC_SS (1-series) = {float(rc_ss_result[1]):.8f}")
                    except Exception as exc:
                        print(f"    [WARN] realized_covariance (1-series, SS=5): {exc}")

                    # Ref: realized_test.m:81 — two series (price,time,price,time), no subsamples
                    try:
                        rc2_result = realized_covariance(
                            [price, price], [time, time],
                            time_type, samp_type, samp_interval
                        )
                        print(f"    RC (2-series) shape = {rc2_result[0].shape}")
                    except Exception as exc:
                        print(f"    [WARN] realized_covariance (2-series): {exc}")

                    # Ref: realized_test.m:82 — two series, subsamples=5
                    try:
                        rc2_ss_result = realized_covariance(
                            [price, price], [time, time],
                            time_type, samp_type, samp_interval,
                            subsamples=5
                        )
                        print(f"    RC_SS (2-series) shape = {rc2_ss_result[1].shape}")
                    except Exception as exc:
                        print(f"    [WARN] realized_covariance (2-series, SS=5): {exc}")

    # ==================================================================
    # Phase 7: Final range estimator calls
    # Ref: realized_test.m:90-91
    # NOTE: In the MATLAB source, 'samplesperbin' and 'overlap' are
    # undefined variables at this point.  Per migration instructions
    # (§0.7.2), provide reasonable defaults:
    #   samplesperbin = 7 (consistent with line 26 usage pattern)
    #   overlap = True (default for realized_range)
    # Ref: realized_test.m:90-91 — realized_range with all params explicit
    # ==================================================================
    print("\n--- Final realized_range tests ---")
    # Use the last sampling_type and sampling_interval from the loop
    # Ref: realized_test.m:90 — after the loop, samplingType='Fixed',
    # samplingInterval=fixedInterval (the last values from the loop)
    final_sampling_type = 'Fixed'
    final_sampling_interval = fixed_interval

    # Ref: realized_test.m:90 — defaults for undefined MATLAB variables
    samples_per_bin_default = 7    # Ref: line 26 pattern
    overlap_default = True         # Ref: realized_range default
    try:
        rr_final, rr_final_ss, rr_final_diag = realized_range(
            price, time, time_type,
            final_sampling_type, final_sampling_interval,
            samples_per_bin=samples_per_bin_default,
            overlap=overlap_default,
            subsamples=subsamples
        )
        print(f"  RR_final = {rr_final:.8f}, RR_final_SS = {rr_final_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_range (final 1): {exc}")

    # Ref: realized_test.m:91 — identical call (duplicated in MATLAB source)
    try:
        rr_final2, rr_final2_ss, rr_final2_diag = realized_range(
            price, time, time_type,
            final_sampling_type, final_sampling_interval,
            samples_per_bin=samples_per_bin_default,
            overlap=overlap_default,
            subsamples=subsamples
        )
        print(f"  RR_final = {rr_final2:.8f}, RR_final_SS = {rr_final2_ss:.8f}")
    except Exception as exc:
        print(f"  [WARN] realized_range (final 2): {exc}")

    print("\n=== realized_test completed successfully ===")


# ---------------------------------------------------------------------------
# Module entry point
# Ref: AAP — script must be runnable as `python -m mfe_toolbox.realized.realized_test`
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    realized_test()
