"""Comprehensive pytest tests for the Generalized Error Distribution (GED) functions.

Tests all 5 GED distribution modules from ``mfe_toolbox.distributions``:
    - gedcdf   — CDF of the GED
    - gedinv   — Inverse CDF (quantile function) of the GED
    - gedloglik — Log-likelihood of the GED
    - gedpdf   — PDF of the GED
    - gedrnd   — Random variate generation from the GED

Per AAP Section 0.7.1:
    - Numerical parity: numpy.testing.assert_allclose(actual, expected, atol=1e-6, rtol=1e-4)
    - Test scalar, vector, and matrix inputs
    - Coverage threshold: >=90% line coverage
    - All tests MUST pass with ``pytest -x --tb=short``
    - GED shape parameter for primary tests: v=1.5
    - Invalid inputs must raise equivalent exceptions

References
----------
.. [1] Tadikamalla (1980), J.Am.Stat.Assoc. (75)
.. [2] Nelson (1991), Econometrica
"""

import numpy as np
import numpy.testing as npt
import pytest
from scipy.integrate import quad
from scipy.stats import norm

from mfe_toolbox.distributions.gedcdf import gedcdf
from mfe_toolbox.distributions.gedinv import gedinv
from mfe_toolbox.distributions.gedloglik import gedloglik
from mfe_toolbox.distributions.gedpdf import gedpdf
from mfe_toolbox.distributions.gedrnd import gedrnd
from tests.conftest import ATOL, RTOL, load_fixture_npy, assert_allclose


# ---------------------------------------------------------------------------
# Fixture loading helper
# ---------------------------------------------------------------------------
def _load_ged_fixture(fixture_dir, name):
    """Load a GED fixture .npy file and extract the dict from 0-D object array.

    The fixture .npy files generated by convert_fixtures.py are stored as
    0-dimensional object arrays wrapping a dict. This helper extracts the
    dict via ``.item()`` for convenient key-based access.

    Parameters
    ----------
    fixture_dir : pathlib.Path
        Path to the distributions fixture directory.
    name : str
        Base name of the fixture file (without .npy extension).

    Returns
    -------
    dict
        Dictionary of fixture data arrays and metadata.
    """
    raw = load_fixture_npy(fixture_dir, name)
    # Handle 0-D object array (dict wrapped in ndarray)
    if raw.ndim == 0 and raw.dtype == object:
        return raw.item()
    return raw


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------
# Primary GED shape parameter per AAP Section 0.7.1
GED_V = 1.5

# Standard test x-grid
X_VECTOR = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])

# Probability values for gedinv tests
P_VECTOR = np.array([0.1, 0.25, 0.5, 0.75, 0.9])


# ---------------------------------------------------------------------------
# Pytest fixtures
# ---------------------------------------------------------------------------
@pytest.fixture
def ged_v():
    """GED shape parameter v=1.5 per AAP."""
    return GED_V


@pytest.fixture
def x_vector():
    """Test vector x=[-2, -1, 0, 1, 2]."""
    return X_VECTOR.copy()


@pytest.fixture
def p_vector():
    """Probability vector for gedinv tests."""
    return P_VECTOR.copy()


@pytest.fixture
def x_data(rng):
    """T=100 random normal data for gedloglik tests (seeded via conftest rng)."""
    return rng.standard_normal(100)


@pytest.fixture
def x_data_large(rng):
    """T=1000 random normal data for larger tests (seeded via conftest rng)."""
    return rng.standard_normal(1000)


# ===========================================================================
# Test Class: gedpdf
# ===========================================================================
class TestGedPdf:
    """Unit, property, and parity tests for the GED probability density function."""

    def test_gedpdf_scalar_v(self, ged_v):
        """Scalar x and scalar v=1.5 should produce a non-negative, finite PDF."""
        x = np.array([0.5])
        v = np.array([ged_v])
        result = gedpdf(x, v)
        assert result.shape == (1,), f"Expected shape (1,), got {result.shape}"
        assert np.all(result >= 0), "PDF must be non-negative"
        assert np.all(np.isfinite(result)), "PDF must be finite for valid inputs"

    def test_gedpdf_vector_input(self, ged_v):
        """Vector x=[-2,-1,0,1,2] with v=1.5; all values >= 0 and finite."""
        x = X_VECTOR.copy()
        v = np.full_like(x, ged_v)
        result = gedpdf(x, v)
        assert result.shape == x.shape, f"Shape mismatch: {result.shape} vs {x.shape}"
        assert np.all(result >= 0), "PDF must be non-negative for all x"
        assert np.all(np.isfinite(result)), "PDF must be finite for valid inputs"

    def test_gedpdf_symmetry(self, ged_v):
        """GED is symmetric: gedpdf(x, v) == gedpdf(-x, v) for all x."""
        x = np.array([0.5, 1.0, 1.5, 2.0, 3.0])
        v = np.full_like(x, ged_v)
        f_pos = gedpdf(x, v)
        f_neg = gedpdf(-x, v)
        npt.assert_allclose(f_pos, f_neg, atol=ATOL, rtol=RTOL,
                            err_msg="GED PDF must be symmetric about zero")

    def test_gedpdf_v_equals_2_is_normal(self):
        """When v=2, GED PDF should match standard normal PDF exactly.

        Ref: Tadikamalla (1980) — GED with v=2 reduces to N(0,1).
        """
        x = np.linspace(-3, 3, 50)
        v = np.full_like(x, 2.0)
        f_ged = gedpdf(x, v)
        f_norm = norm.pdf(x)
        npt.assert_allclose(f_ged, f_norm, atol=1e-10, rtol=1e-10,
                            err_msg="GED(v=2) must match standard normal PDF")

    def test_gedpdf_nan_for_invalid_v(self):
        """v < 1 should produce NaN output."""
        x = np.array([0.0, 1.0, -1.0])
        v = np.full_like(x, 0.5)
        result = gedpdf(x, v)
        assert np.all(np.isnan(result)), "v<1 must produce NaN for all elements"

    def test_gedpdf_integrates_to_one(self, ged_v):
        """Numerical integration of gedpdf over [-10, 10] should ≈ 1.0."""
        integral, _ = quad(
            lambda t: float(gedpdf(np.array([t]), np.array([ged_v]))[0]),
            -10.0, 10.0
        )
        npt.assert_allclose(integral, 1.0, atol=1e-6,
                            err_msg="GED PDF must integrate to 1.0")

    def test_gedpdf_integrates_to_one_v2(self):
        """Integration of gedpdf with v=2 (normal) over wide range."""
        integral, _ = quad(
            lambda t: float(gedpdf(np.array([t]), np.array([2.0]))[0]),
            -10.0, 10.0
        )
        npt.assert_allclose(integral, 1.0, atol=1e-10,
                            err_msg="GED(v=2) PDF must integrate to 1.0")

    def test_gedpdf_integrates_to_one_v1(self):
        """Integration of gedpdf with v=1 (Laplace) over wide range."""
        integral, _ = quad(
            lambda t: float(gedpdf(np.array([t]), np.array([1.0]))[0]),
            -15.0, 15.0
        )
        npt.assert_allclose(integral, 1.0, atol=1e-6,
                            err_msg="GED(v=1) PDF must integrate to 1.0")

    def test_gedpdf_non_negative_dense_grid(self, ged_v):
        """PDF >= 0 across a dense grid of 200 points."""
        x = np.linspace(-5, 5, 200)
        v = np.full_like(x, ged_v)
        result = gedpdf(x, v)
        assert np.all(result >= 0), "PDF must be non-negative everywhere"

    def test_gedpdf_peak_at_zero(self, ged_v):
        """PDF should attain its maximum at x=0 for symmetric GED."""
        x = np.array([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0])
        v = np.full_like(x, ged_v)
        f = gedpdf(x, v)
        # Index 3 is x=0
        assert f[3] >= f[0], "PDF at 0 must be >= PDF at -2"
        assert f[3] >= f[1], "PDF at 0 must be >= PDF at -1"
        assert f[3] >= f[4], "PDF at 0 must be >= PDF at 0.5"
        assert f[3] >= f[6], "PDF at 0 must be >= PDF at 2"

    def test_gedpdf_scalar_input(self):
        """Scalar x=0.0, v=2.0 should produce result matching 1/sqrt(2*pi)."""
        result = gedpdf(0.0, 2.0)
        expected = 1.0 / np.sqrt(2.0 * np.pi)
        npt.assert_allclose(np.asarray(result).flat[0], expected, atol=1e-10)

    def test_gedpdf_tail_decay(self, ged_v):
        """PDF should decrease as |x| increases from the mode."""
        x_abs = np.array([0.0, 0.5, 1.0, 2.0, 3.0, 5.0])
        v = np.full_like(x_abs, ged_v)
        f = gedpdf(x_abs, v)
        # Each successive value should be <= the previous
        for i in range(1, len(f)):
            assert f[i] <= f[i - 1] + 1e-15, \
                f"PDF should decay in the tail: f({x_abs[i]})={f[i]} > f({x_abs[i-1]})={f[i-1]}"

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedpdf_parity_case1(self, distributions_fixture_dir):
        """Parity: gedpdf with v=1.5 against MATLAB reference fixture."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedpdf")
        x = fixture['x']
        v_val = float(fixture['case1_v'])
        expected = fixture['case1_gedpdf_out']
        v = np.full_like(x, v_val)
        actual = gedpdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedpdf case1 (v=1.5) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedpdf_parity_case2(self, distributions_fixture_dir):
        """Parity: gedpdf with v=1.0 (Laplace) against MATLAB reference fixture."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedpdf")
        x = fixture['x']
        v_val = float(fixture['case2_v'])
        expected = fixture['case2_gedpdf_out']
        v = np.full_like(x, v_val)
        actual = gedpdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedpdf case2 (v=1.0) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedpdf_parity_case3(self, distributions_fixture_dir):
        """Parity: gedpdf with v=2.0 (Normal) against MATLAB reference fixture."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedpdf")
        x = fixture['x']
        v_val = float(fixture['case3_v'])
        expected = fixture['case3_gedpdf_out']
        v = np.full_like(x, v_val)
        actual = gedpdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedpdf case3 (v=2.0) parity failure")


# ===========================================================================
# Test Class: gedcdf
# ===========================================================================
class TestGedCdf:
    """Unit, property, and parity tests for the GED cumulative distribution function."""

    def test_gedcdf_scalar_zero(self, ged_v):
        """CDF at x=0 should be 0.5 (symmetry of GED)."""
        result = gedcdf(np.array([0.0]), np.array([ged_v]))
        npt.assert_allclose(result, 0.5, atol=ATOL,
                            err_msg="CDF(0) must be 0.5 for symmetric GED")

    def test_gedcdf_vector_monotonic(self, ged_v):
        """CDF should be monotonically non-decreasing over a sorted x vector."""
        x = np.linspace(-4, 4, 50)
        v = np.full_like(x, ged_v)
        p = gedcdf(x, v)
        diffs = np.diff(p)
        assert np.all(diffs >= -1e-12), "CDF must be monotonically non-decreasing"

    def test_gedcdf_bounds(self, ged_v):
        """CDF values should be in [0, 1] for all x."""
        x = np.linspace(-10, 10, 100)
        v = np.full_like(x, ged_v)
        p = gedcdf(x, v)
        assert np.all(p >= 0.0), "CDF must be >= 0"
        assert np.all(p <= 1.0), "CDF must be <= 1"

    def test_gedcdf_symmetry(self, ged_v):
        """gedcdf(x, v) + gedcdf(-x, v) ≈ 1.0 for symmetric GED."""
        x = np.array([0.5, 1.0, 1.5, 2.0, 3.0])
        v = np.full_like(x, ged_v)
        p_pos = gedcdf(x, v)
        p_neg = gedcdf(-x, v)
        npt.assert_allclose(p_pos + p_neg, 1.0, atol=ATOL,
                            err_msg="CDF symmetry: CDF(x) + CDF(-x) must ≈ 1")

    def test_gedcdf_nan_for_invalid_v(self):
        """v < 1 should produce NaN."""
        x = np.array([0.0, 1.0, -1.0])
        v = np.full_like(x, 0.5)
        result = gedcdf(x, v)
        assert np.all(np.isnan(result)), "v<1 must produce NaN"

    def test_gedcdf_large_positive_x(self, ged_v):
        """CDF should approach 1 for large positive x."""
        x = np.array([10.0, 20.0, 50.0])
        v = np.full_like(x, ged_v)
        p = gedcdf(x, v)
        npt.assert_allclose(p, 1.0, atol=1e-6,
                            err_msg="CDF must approach 1 for large positive x")

    def test_gedcdf_large_negative_x(self, ged_v):
        """CDF should approach 0 for large negative x."""
        x = np.array([-10.0, -20.0, -50.0])
        v = np.full_like(x, ged_v)
        p = gedcdf(x, v)
        npt.assert_allclose(p, 0.0, atol=1e-6,
                            err_msg="CDF must approach 0 for large negative x")

    def test_gedcdf_v_equals_2_is_normal(self):
        """When v=2, GED CDF should match standard normal CDF."""
        x = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
        v = np.full_like(x, 2.0)
        p_ged = gedcdf(x, v)
        p_norm = norm.cdf(x)
        npt.assert_allclose(p_ged, p_norm, atol=1e-6,
                            err_msg="GED(v=2) CDF must match normal CDF")

    def test_gedcdf_scalar_input(self):
        """Scalar x and v should work correctly."""
        p = gedcdf(0.0, 2.0)
        npt.assert_allclose(np.asarray(p).flat[0], 0.5, atol=1e-10)

    def test_gedcdf_v_equals_1_at_zero(self):
        """CDF(0) = 0.5 for v=1 (Laplace) as well."""
        p = gedcdf(np.array([0.0]), np.array([1.0]))
        npt.assert_allclose(p, 0.5, atol=ATOL)

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_case1(self, distributions_fixture_dir):
        """Parity: gedcdf with v=1.5 against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x = fixture['x']
        v_val = float(fixture['case1_v'])
        expected = fixture['case1_gedcdf_out']
        v = np.full_like(x, v_val)
        actual = gedcdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedcdf case1 (v=1.5) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_case2(self, distributions_fixture_dir):
        """Parity: gedcdf with v=1.0 (Laplace) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x = fixture['x']
        v_val = float(fixture['case2_v'])
        expected = fixture['case2_gedcdf_out']
        v = np.full_like(x, v_val)
        actual = gedcdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedcdf case2 (v=1.0) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_case3(self, distributions_fixture_dir):
        """Parity: gedcdf with v=2.0 (Normal) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x = fixture['x']
        v_val = float(fixture['case3_v'])
        expected = fixture['case3_gedcdf_out']
        v = np.full_like(x, v_val)
        actual = gedcdf(x, v)
        assert_allclose(actual, expected,
                        err_msg="gedcdf case3 (v=2.0) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_tails(self, distributions_fixture_dir):
        """Parity: gedcdf at tail x values (v=1.5) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x_tails = fixture['x_tails']
        expected_v1p5 = fixture['p_tails_v1p5']
        v = np.full_like(x_tails, 1.5)
        actual = gedcdf(x_tails, v)
        assert_allclose(actual, expected_v1p5,
                        err_msg="gedcdf tail parity failure (v=1.5)")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_edges(self, distributions_fixture_dir):
        """Parity: gedcdf at edge x values (small positive) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x_edge = fixture['x_edge']
        expected = fixture['p_edge_v1p5']
        v = np.full_like(x_edge, 1.5)
        actual = gedcdf(x_edge, v)
        assert_allclose(actual, expected,
                        err_msg="gedcdf edge parity failure (v=1.5)")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_scalar(self, distributions_fixture_dir):
        """Parity: scalar gedcdf against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        scalar_x = float(fixture['scalar_x'])
        scalar_v = float(fixture['scalar_v'])
        expected = float(fixture['scalar_gedcdf_out'])
        actual = gedcdf(scalar_x, scalar_v)
        npt.assert_allclose(float(np.asarray(actual).flat[0]), expected,
                            atol=ATOL, rtol=RTOL,
                            err_msg="gedcdf scalar parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedcdf_parity_invalid_v(self, distributions_fixture_dir):
        """Parity: gedcdf with v < 1 returns NaN as in MATLAB."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedcdf")
        x_inv = fixture['v_lt1_x']
        v_inv = float(fixture['v_lt1_v'])
        expected = fixture['v_lt1_result']
        v = np.full_like(x_inv, v_inv)
        actual = gedcdf(x_inv, v)
        # Both should be NaN
        assert np.all(np.isnan(actual)), "v<1 must produce NaN (parity)"
        assert np.all(np.isnan(expected)), "Fixture should also contain NaN"


# ===========================================================================
# Test Class: gedinv
# ===========================================================================
class TestGedInv:
    """Unit, property, and parity tests for the GED inverse CDF (quantile function)."""

    def test_gedinv_scalar_median(self, ged_v):
        """Quantile at p=0.5 should be 0 (symmetric distribution median)."""
        result = gedinv(np.array([0.5]), np.array([ged_v]))
        npt.assert_allclose(result, 0.0, atol=ATOL,
                            err_msg="gedinv(0.5, v) must be 0 (median)")

    def test_gedinv_vector_monotonic(self, ged_v):
        """Quantile function should be monotonically non-decreasing."""
        p = np.linspace(0.01, 0.99, 50)
        v = np.full_like(p, ged_v)
        x = gedinv(p, v)
        diffs = np.diff(x)
        assert np.all(diffs >= -1e-10), "Quantile function must be non-decreasing"

    def test_gedinv_boundary_p0(self, ged_v):
        """gedinv(0, v) should return 0 for valid v.

        Ref: gedinv.m:57-60 — p==0 with valid v -> x = 0.
        """
        result = gedinv(np.array([0.0]), np.array([ged_v]))
        npt.assert_allclose(result, 0.0, atol=ATOL,
                            err_msg="gedinv(0, v) must be 0")

    def test_gedinv_boundary_p1(self, ged_v):
        """gedinv(1, v) should return +Inf for valid v.

        Ref: gedinv.m:62-66 — p==1 with valid v -> x = Inf.
        """
        result = gedinv(np.array([1.0]), np.array([ged_v]))
        assert np.all(np.isinf(result) & (result > 0)), \
            f"gedinv(1, v) must be +Inf, got {result}"

    def test_gedinv_inverse_consistency(self, ged_v):
        """gedinv(gedcdf(x, v), v) ≈ x within tolerance (CDF→INV roundtrip)."""
        x_orig = np.array([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0])
        v = np.full_like(x_orig, ged_v)
        p = gedcdf(x_orig, v)
        x_recovered = gedinv(p, v)
        npt.assert_allclose(x_recovered, x_orig, atol=1e-5, rtol=1e-4,
                            err_msg="CDF→INV roundtrip must recover original x")

    def test_gedinv_nan_for_invalid_v(self):
        """v < 1 should produce NaN."""
        p = np.array([0.1, 0.5, 0.9])
        v = np.full_like(p, 0.5)
        result = gedinv(p, v)
        assert np.all(np.isnan(result)), "v<1 must produce NaN"

    def test_gedinv_nan_for_invalid_p(self, ged_v):
        """p outside [0, 1] should produce NaN."""
        p = np.array([-0.1, 1.5])
        v = np.full_like(p, ged_v)
        result = gedinv(p, v)
        assert np.all(np.isnan(result)), "p outside [0,1] must produce NaN"

    def test_gedinv_symmetry(self, ged_v):
        """gedinv(p, v) = -gedinv(1-p, v) for symmetric distribution."""
        p = np.array([0.1, 0.2, 0.3, 0.4])
        v = np.full_like(p, ged_v)
        lower = gedinv(p, v)
        upper = gedinv(1.0 - p, v)
        npt.assert_allclose(lower, -upper, atol=1e-5, rtol=1e-4,
                            err_msg="gedinv symmetry: gedinv(p) = -gedinv(1-p)")

    def test_gedinv_v_equals_2_is_normal(self):
        """When v=2, gedinv should match standard normal quantiles."""
        p = np.array([0.025, 0.1, 0.25, 0.5, 0.75, 0.9, 0.975])
        v = np.full_like(p, 2.0)
        x_ged = gedinv(p, v)
        x_norm = norm.ppf(p)
        npt.assert_allclose(x_ged, x_norm, atol=1e-5, rtol=1e-4,
                            err_msg="GED(v=2) quantiles must match normal quantiles")

    def test_gedinv_scalar_input(self):
        """Scalar p=0.5, v=2.0 should return 0."""
        result = gedinv(0.5, 2.0)
        npt.assert_allclose(np.asarray(result).flat[0], 0.0, atol=ATOL)

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_case1(self, distributions_fixture_dir):
        """Parity: gedinv with v=1.5 against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        p = fixture['p']
        v_val = float(fixture['case1_v'])
        expected = fixture['case1_gedinv_out']
        v = np.full_like(p, v_val)
        actual = gedinv(p, v)
        assert_allclose(actual, expected,
                        err_msg="gedinv case1 (v=1.5) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_case2(self, distributions_fixture_dir):
        """Parity: gedinv with v=1.0 (Laplace) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        p = fixture['p']
        v_val = float(fixture['case2_v'])
        expected = fixture['case2_gedinv_out']
        v = np.full_like(p, v_val)
        actual = gedinv(p, v)
        assert_allclose(actual, expected,
                        err_msg="gedinv case2 (v=1.0) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_case3(self, distributions_fixture_dir):
        """Parity: gedinv with v=2.0 (Normal) against MATLAB reference."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        p = fixture['p']
        v_val = float(fixture['case3_v'])
        expected = fixture['case3_gedinv_out']
        v = np.full_like(p, v_val)
        actual = gedinv(p, v)
        assert_allclose(actual, expected,
                        err_msg="gedinv case3 (v=2.0) parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_roundtrip(self, distributions_fixture_dir):
        """Parity: gedinv -> gedcdf roundtrip recovers original probabilities."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        expected_p = fixture['roundtrip_p_case1']
        x_out = fixture['case1_gedinv_out']
        v_val = float(fixture['case1_v'])
        v = np.full_like(x_out, v_val)
        actual_p = gedcdf(x_out, v)
        assert_allclose(actual_p, expected_p,
                        err_msg="gedinv roundtrip parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_boundary(self, distributions_fixture_dir):
        """Parity: boundary values p=0 -> 0, p=1 -> +Inf."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        expected_p0 = float(fixture['boundary_p0'])
        expected_p1 = float(fixture['boundary_p1'])
        actual_p0 = gedinv(np.array([0.0]), np.array([1.5]))
        npt.assert_allclose(float(actual_p0[0]), expected_p0, atol=ATOL,
                            err_msg="gedinv boundary p=0 parity failure")
        actual_p1 = gedinv(np.array([1.0]), np.array([1.5]))
        assert np.isinf(actual_p1[0]) and actual_p1[0] > 0, \
            f"Expected +Inf for p=1, got {actual_p1[0]}"

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_symmetry(self, distributions_fixture_dir):
        """Parity: symmetry of quantiles from fixture."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        lower = fixture['symmetry_check_lower']
        upper = fixture['symmetry_check_upper']
        npt.assert_allclose(lower, -upper, atol=1e-5, rtol=1e-4,
                            err_msg="gedinv fixture symmetry check failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedinv_parity_invalid_v(self, distributions_fixture_dir):
        """Parity: gedinv with v < 1 returns NaN."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedinv")
        expected = fixture['v_lt_1_result']
        # gedinv at [0.1, 0.5, 0.9, 0.01, 0.99] with v < 1 -> all NaN
        p = np.array([0.1, 0.5, 0.9, 0.01, 0.99])
        v = np.full_like(p, 0.5)
        actual = gedinv(p, v)
        assert np.all(np.isnan(actual)), "v<1 must produce NaN (parity)"
        assert np.all(np.isnan(expected)), "Fixture should also contain NaN"


# ===========================================================================
# Test Class: gedloglik
# ===========================================================================
class TestGedLoglik:
    """Unit, property, and parity tests for the GED log-likelihood function."""

    def test_gedloglik_scalar_sigma(self, x_data, ged_v):
        """Scalar sigma2=1.0 returns (LL, lls) with sum(lls) ≈ LL."""
        LL, lls = gedloglik(x_data, 0.0, 1.0, ged_v)
        assert np.isfinite(LL), "Total LL must be finite"
        assert lls.shape == x_data.shape, \
            f"lls shape {lls.shape} must match x shape {x_data.shape}"
        npt.assert_allclose(np.sum(lls), LL, atol=1e-8,
                            err_msg="sum(lls) must equal LL")

    def test_gedloglik_vector_sigma(self, x_data, ged_v):
        """Vector sigma2 (T-length) returns consistent LL and lls."""
        T = len(x_data)
        sigma2 = np.full(T, 1.5)
        LL, lls = gedloglik(x_data, 0.0, sigma2, ged_v)
        assert np.isfinite(LL), "Total LL must be finite"
        assert lls.shape == (T,)
        npt.assert_allclose(np.sum(lls), LL, atol=1e-8,
                            err_msg="sum(lls) must equal LL for vector sigma2")

    def test_gedloglik_v_equals_2_matches_normal(self, x_data):
        """When v=2, GED log-likelihood should match normal log-likelihood.

        Ref: GED(v=2) = N(0, sigma2), so gedloglik(x, 0, 1, 2) = sum(norm.logpdf(x)).
        """
        LL_ged, lls_ged = gedloglik(x_data, 0.0, 1.0, 2.0)
        lls_norm = norm.logpdf(x_data)
        LL_norm = np.sum(lls_norm)
        npt.assert_allclose(LL_ged, LL_norm, atol=1e-6, rtol=1e-4,
                            err_msg="GED(v=2) LL must match normal LL")
        npt.assert_allclose(lls_ged, lls_norm, atol=1e-6, rtol=1e-4,
                            err_msg="GED(v=2) lls must match normal lls")

    def test_gedloglik_sum_consistency(self, x_data, ged_v):
        """Verify np.sum(lls) ≈ LL using assert_allclose."""
        LL, lls = gedloglik(x_data, 0.0, 1.0, ged_v)
        assert_allclose(np.array([np.sum(lls)]), np.array([LL]),
                        err_msg="sum(lls) vs LL consistency check")

    def test_gedloglik_invalid_v_raises(self, x_data):
        """v <= 1 should raise ValueError.

        Ref: gedloglik.m:53-54 — length(v)>1 || v<=1 -> error
        """
        with pytest.raises(ValueError, match="greater than 1"):
            gedloglik(x_data, 0.0, 1.0, 1.0)
        with pytest.raises(ValueError, match="greater than 1"):
            gedloglik(x_data, 0.0, 1.0, 0.5)

    def test_gedloglik_invalid_v_negative_raises(self, x_data):
        """Negative v should raise ValueError."""
        with pytest.raises(ValueError, match="greater than 1"):
            gedloglik(x_data, 0.0, 1.0, -2.0)

    def test_gedloglik_invalid_sigma2_zero_raises(self, x_data, ged_v):
        """sigma2 = 0 should raise ValueError."""
        with pytest.raises(ValueError, match="positive"):
            gedloglik(x_data, 0.0, 0.0, ged_v)

    def test_gedloglik_invalid_sigma2_negative_raises(self, x_data, ged_v):
        """sigma2 < 0 should raise ValueError."""
        with pytest.raises(ValueError, match="positive"):
            gedloglik(x_data, 0.0, -1.0, ged_v)

    def test_gedloglik_invalid_sigma2_vector_raises(self, x_data, ged_v):
        """sigma2 vector with any non-positive element should raise ValueError."""
        T = len(x_data)
        sigma2 = np.ones(T)
        sigma2[50] = -0.1
        with pytest.raises(ValueError, match="positive"):
            gedloglik(x_data, 0.0, sigma2, ged_v)

    def test_gedloglik_returns_finite(self, x_data, ged_v):
        """LL and all lls should be finite for valid inputs."""
        LL, lls = gedloglik(x_data, 0.0, 1.0, ged_v)
        assert np.isfinite(LL), "Total LL must be finite"
        assert np.all(np.isfinite(lls)), "All individual lls must be finite"

    def test_gedloglik_negative(self, x_data, ged_v):
        """Log-likelihood for unit variance data should be negative."""
        LL, _ = gedloglik(x_data, 0.0, 1.0, ged_v)
        assert LL < 0, "LL for unit variance normal data should be negative"

    def test_gedloglik_mu_shift(self, x_data, ged_v):
        """Shifting mu far from data mean should decrease log-likelihood."""
        LL1, _ = gedloglik(x_data, 0.0, 1.0, ged_v)
        LL2, _ = gedloglik(x_data, 5.0, 1.0, ged_v)
        assert LL1 > LL2, "LL should decrease when mu is far from data mean"

    def test_gedloglik_higher_variance_lower_ll(self, x_data, ged_v):
        """Higher sigma2 should produce different LL (likelihood tradeoff)."""
        LL_low, _ = gedloglik(x_data, 0.0, 1.0, ged_v)
        LL_high, _ = gedloglik(x_data, 0.0, 10.0, ged_v)
        # For unit-variance data, sigma2=1 should be better fit
        assert LL_low > LL_high, \
            "LL(sigma2=1) should be higher than LL(sigma2=10) for unit-var data"

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedloglik_parity_case1(self, distributions_fixture_dir):
        """Parity: gedloglik case1 (mu=0, sigma2=1, v=1.5)."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedloglik")
        x = fixture['x']
        v = float(fixture['v'])
        mu = float(fixture['case1_mu'])
        sigma2 = float(fixture['case1_sigma2'])
        expected_LL = float(fixture['case1_LL'])
        expected_lls = fixture['case1_lls']
        LL, lls = gedloglik(x, mu, sigma2, v)
        npt.assert_allclose(LL, expected_LL, atol=ATOL, rtol=RTOL,
                            err_msg="gedloglik case1 LL parity failure")
        assert_allclose(lls, expected_lls,
                        err_msg="gedloglik case1 lls parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedloglik_parity_case2(self, distributions_fixture_dir):
        """Parity: gedloglik case2 (mu=0.5, sigma2=1, v=1.5)."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedloglik")
        x = fixture['x']
        v = float(fixture['v'])
        mu = float(fixture['case2_mu'])
        sigma2 = float(fixture['case2_sigma2'])
        expected_LL = float(fixture['case2_LL'])
        expected_lls = fixture['case2_lls']
        LL, lls = gedloglik(x, mu, sigma2, v)
        npt.assert_allclose(LL, expected_LL, atol=ATOL, rtol=RTOL,
                            err_msg="gedloglik case2 LL parity failure")
        assert_allclose(lls, expected_lls,
                        err_msg="gedloglik case2 lls parity failure")

    @pytest.mark.parity
    @pytest.mark.requires_fixtures
    def test_gedloglik_parity_case3(self, distributions_fixture_dir):
        """Parity: gedloglik case3 (mu=0, sigma2=1.5, v=1.5)."""
        fixture = _load_ged_fixture(distributions_fixture_dir, "gedloglik")
        x = fixture['x']
        v = float(fixture['v'])
        mu = float(fixture['case3_mu'])
        sigma2 = float(fixture['case3_sigma2'])
        expected_LL = float(fixture['case3_LL'])
        expected_lls = fixture['case3_lls']
        LL, lls = gedloglik(x, mu, sigma2, v)
        npt.assert_allclose(LL, expected_LL, atol=ATOL, rtol=RTOL,
                            err_msg="gedloglik case3 LL parity failure")
        assert_allclose(lls, expected_lls,
                        err_msg="gedloglik case3 lls parity failure")


# ===========================================================================
# Test Class: gedrnd
# ===========================================================================
class TestGedRnd:
    """Unit, property, and statistical tests for GED random variate generation."""

    def test_gedrnd_shape_2d(self, ged_v):
        """gedrnd(v, m, n) returns array of shape (m, n)."""
        r = gedrnd(ged_v, 100, 1)
        assert r.shape == (100, 1), f"Expected (100, 1), got {r.shape}"

    def test_gedrnd_shape_1d(self, ged_v):
        """gedrnd(v, n) returns 1-D array of length n."""
        r = gedrnd(ged_v, 200)
        assert r.shape == (200,), f"Expected (200,), got {r.shape}"

    def test_gedrnd_nan_for_invalid_v(self):
        """v < 1 should produce NaN values."""
        r = gedrnd(0.5, 10)
        assert np.all(np.isnan(r)), "v<1 must produce NaN in all elements"

    def test_gedrnd_statistical_properties(self, ged_v):
        """Large sample: mean ≈ 0, variance ≈ 1 (loose tolerance ~0.05)."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(ged_v, 50000, rng=rng_local)
        npt.assert_allclose(np.mean(r), 0.0, atol=0.05,
                            err_msg="GED mean should be ~0")
        npt.assert_allclose(np.var(r), 1.0, atol=0.1,
                            err_msg="GED variance should be ~1")

    def test_gedrnd_reproducibility(self, ged_v):
        """Same RNG seed produces identical output."""
        rng1 = np.random.default_rng(123)
        rng2 = np.random.default_rng(123)
        r1 = gedrnd(ged_v, 100, rng=rng1)
        r2 = gedrnd(ged_v, 100, rng=rng2)
        npt.assert_array_equal(r1, r2,
                               err_msg="Same seed must produce identical output")

    def test_gedrnd_returns_ndarray(self, ged_v):
        """Return type must be numpy.ndarray."""
        r = gedrnd(ged_v, 10)
        assert isinstance(r, np.ndarray), f"Expected ndarray, got {type(r)}"

    def test_gedrnd_v_equals_2_normal_like(self):
        """GED(v=2) random variates should have approximately normal statistics."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(2.0, 50000, rng=rng_local)
        npt.assert_allclose(np.mean(r), 0.0, atol=0.05)
        npt.assert_allclose(np.var(r), 1.0, atol=0.1)

    def test_gedrnd_v_equals_1_laplace_like(self):
        """GED(v=1) random variates should have Laplace-like excess kurtosis ≈ 3."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(1.0, 100000, rng=rng_local)
        npt.assert_allclose(np.mean(r), 0.0, atol=0.05)
        npt.assert_allclose(np.var(r), 1.0, atol=0.1)
        # Laplace excess kurtosis = 3
        from scipy.stats import kurtosis as scipy_kurtosis
        kurt = scipy_kurtosis(r, fisher=True)
        npt.assert_allclose(kurt, 3.0, atol=0.5,
                            err_msg="GED(v=1) excess kurtosis should be ~3")

    def test_gedrnd_scalar_v_no_size(self):
        """Scalar v with no size args should produce (1,1) shape."""
        r = gedrnd(2.0)
        assert r.shape == (1, 1), f"Expected (1, 1) for scalar v, got {r.shape}"

    def test_gedrnd_different_seeds_different_output(self, ged_v):
        """Different RNG seeds should produce different output."""
        rng1 = np.random.default_rng(1)
        rng2 = np.random.default_rng(2)
        r1 = gedrnd(ged_v, 100, rng=rng1)
        r2 = gedrnd(ged_v, 100, rng=rng2)
        assert not np.allclose(r1, r2), "Different seeds should give different results"

    def test_gedrnd_large_v_thin_tails(self):
        """Large v should produce thin-tailed (sub-Gaussian) variates."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(10.0, 50000, rng=rng_local)
        # Large v -> thin tails -> lower excess kurtosis (negative)
        from scipy.stats import kurtosis as scipy_kurtosis
        kurt = scipy_kurtosis(r, fisher=True)
        assert kurt < 0, f"GED(v=10) should have negative excess kurtosis, got {kurt}"

    def test_gedrnd_all_finite_for_valid_v(self, ged_v):
        """All generated values should be finite for valid v."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(ged_v, 1000, rng=rng_local)
        assert np.all(np.isfinite(r)), "All values must be finite for valid v"


# ===========================================================================
# Integration Tests
# ===========================================================================
class TestGedIntegration:
    """Cross-function integration tests for GED distribution consistency."""

    def test_cdf_pdf_consistency(self, ged_v):
        """Numerical derivative of CDF ≈ PDF (central finite difference).

        dCDF/dx ≈ (CDF(x+h) - CDF(x-h)) / (2h) should match PDF(x).
        """
        h = 1e-5
        x_test = np.array([-1.5, -0.5, 0.0, 0.5, 1.5])
        for xi in x_test:
            cdf_plus = gedcdf(np.array([xi + h]), np.array([ged_v]))[0]
            cdf_minus = gedcdf(np.array([xi - h]), np.array([ged_v]))[0]
            numerical_pdf = (cdf_plus - cdf_minus) / (2.0 * h)
            analytical_pdf = gedpdf(np.array([xi]), np.array([ged_v]))[0]
            npt.assert_allclose(
                numerical_pdf, analytical_pdf, atol=1e-4, rtol=1e-3,
                err_msg=f"CDF derivative must ≈ PDF at x={xi}"
            )

    def test_cdf_inv_roundtrip(self, ged_v):
        """gedcdf(gedinv(p, v), v) ≈ p for p in (0.01, 0.99)."""
        p_test = np.array([0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99])
        v = np.full_like(p_test, ged_v)
        x_inv = gedinv(p_test, v)
        p_recovered = gedcdf(x_inv, v)
        npt.assert_allclose(p_recovered, p_test, atol=1e-5, rtol=1e-4,
                            err_msg="CDF(INV(p)) must recover p")

    def test_inv_cdf_roundtrip(self, ged_v):
        """gedinv(gedcdf(x, v), v) ≈ x for moderate x values."""
        x_test = np.array([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0])
        v = np.full_like(x_test, ged_v)
        p = gedcdf(x_test, v)
        x_recovered = gedinv(p, v)
        npt.assert_allclose(x_recovered, x_test, atol=1e-5, rtol=1e-4,
                            err_msg="INV(CDF(x)) must recover x")

    def test_loglik_pdf_consistency(self, ged_v):
        """exp(lls[i]) ≈ gedpdf(z[i], v) / sqrt(sigma2[i]).

        The log-likelihood at observation i for the GED(mu, sigma2, v) is:
            lls[i] = log(gedpdf(z[i], v) / sqrt(sigma2[i]))
        where z[i] = (x[i] - mu) / sqrt(sigma2[i]).
        """
        rng_local = np.random.default_rng(42)
        x = rng_local.standard_normal(20)
        sigma2 = np.ones(20)
        mu = 0.0
        _, lls = gedloglik(x, mu, sigma2, ged_v)
        z = (x - mu) / np.sqrt(sigma2)
        for i in range(len(x)):
            pdf_val = gedpdf(np.array([z[i]]), np.array([ged_v]))[0]
            expected_ll = np.log(pdf_val / np.sqrt(sigma2[i]))
            npt.assert_allclose(
                lls[i], expected_ll, atol=1e-6, rtol=1e-4,
                err_msg=f"loglik-PDF consistency failed at i={i}"
            )

    def test_loglik_pdf_consistency_varying_sigma(self, ged_v):
        """loglik-PDF consistency with varying sigma2 values."""
        rng_local = np.random.default_rng(99)
        x = rng_local.standard_normal(15)
        sigma2 = 0.5 + rng_local.random(15) * 2.0  # sigma2 in [0.5, 2.5]
        mu = 0.0
        _, lls = gedloglik(x, mu, sigma2, ged_v)
        z = (x - mu) / np.sqrt(sigma2)
        for i in range(len(x)):
            pdf_val = gedpdf(np.array([z[i]]), np.array([ged_v]))[0]
            expected_ll = np.log(pdf_val / np.sqrt(sigma2[i]))
            npt.assert_allclose(
                lls[i], expected_ll, atol=1e-5, rtol=1e-3,
                err_msg=f"loglik-PDF consistency (varying sigma) failed at i={i}"
            )

    def test_multiple_v_values_consistency(self):
        """Test CDF/PDF/INV consistency across multiple v values: 1.0, 1.5, 2.0, 3.0."""
        for v_val in [1.0, 1.5, 2.0, 3.0]:
            x = np.linspace(-3, 3, 20)
            v = np.full_like(x, v_val)

            # gedpdf: non-negative
            f = gedpdf(x, v)
            assert np.all(f >= 0), f"gedpdf must be >= 0 for v={v_val}"

            # gedcdf: in [0, 1]
            p = gedcdf(x, v)
            assert np.all(p >= 0) and np.all(p <= 1), \
                f"gedcdf must be in [0,1] for v={v_val}"

            # gedcdf monotonic
            assert np.all(np.diff(p) >= -1e-10), \
                f"gedcdf must be non-decreasing for v={v_val}"

            # gedinv roundtrip
            p_test = np.array([0.1, 0.5, 0.9])
            v_test = np.full_like(p_test, v_val)
            x_inv = gedinv(p_test, v_test)
            p_rec = gedcdf(x_inv, v_test)
            npt.assert_allclose(p_rec, p_test, atol=1e-4, rtol=1e-3,
                                err_msg=f"CDF-INV roundtrip failed for v={v_val}")

    def test_random_variates_cdf_uniformity(self, ged_v):
        """CDF of GED random variates should be approximately uniform on [0,1]."""
        rng_local = np.random.default_rng(42)
        r = gedrnd(ged_v, 5000, rng=rng_local)
        v = np.full_like(r, ged_v)
        u = gedcdf(r, v)
        # U should be approximately Uniform(0,1): mean ≈ 0.5, var ≈ 1/12
        npt.assert_allclose(np.mean(u), 0.5, atol=0.05,
                            err_msg="CDF(GED samples) mean should be ~0.5")
        npt.assert_allclose(np.var(u), 1.0 / 12.0, atol=0.02,
                            err_msg="CDF(GED samples) variance should be ~1/12")
